// คลังข้อมูลระบบสอบ DL — สำนักงานบุคคล SPU
// คลังข้อสอบ 120 ข้อ นำเข้าจาก SPU_DL_Question_Bank_120 (01/08/69)
window.DL_DATA = {
  categories: {
    FND: "พื้นฐานดิจิทัลและการเข้าถึง",
    PRD: "เครื่องมือสำนักงานและการทำงานร่วมกัน",
    INF: "การรู้สารสนเทศ ข้อมูล และสื่อ",
    COM: "การสื่อสารและประสานงานดิจิทัล",
    SEC: "ความมั่นคงปลอดภัยไซเบอร์",
    PRI: "ข้อมูลส่วนบุคคลและสิทธิดิจิทัล",
    CIT: "พลเมืองดิจิทัลและสุขภาวะ",
    DTR: "ธุรกรรมดิจิทัลและลิขสิทธิ์",
    AIL: "การใช้และรู้เท่าทัน AI",
    PRB: "การแก้ปัญหาและระบบอัตโนมัติ"
  },
  categoryScope: {
    FND: "เข้าใจอุปกรณ์ ซอฟต์แวร์ อินเทอร์เน็ต ไฟล์ คลาวด์ และการเข้าถึงบริการดิจิทัล",
    PRD: "เลือกและใช้เอกสาร ตารางคำนวณ งานนำเสนอ ปฏิทิน และพื้นที่ทำงานร่วมกัน",
    INF: "ค้นหา ตรวจสอบ วิเคราะห์ อ้างอิง และสื่อสารข้อมูลอย่างมีวิจารณญาณ",
    COM: "เลือกช่องทาง สื่อสารอย่างเหมาะสม จัดประชุม และทำงานออนไลน์อย่างรับผิดชอบ",
    SEC: "รหัสผ่าน MFA ฟิชชิง มัลแวร์ การอัปเดต การรายงานเหตุ และการกู้คืน",
    PRI: "ลดการเก็บข้อมูล จำกัดสิทธิ์ ใช้ตามวัตถุประสงค์ และจัดการเหตุข้อมูลรั่วไหล",
    CIT: "รอยเท้าดิจิทัล การกลั่นแกล้ง ความรับผิดชอบ สุขภาพดิจิทัล และ accessibility",
    DTR: "ซื้อขายออนไลน์ ลายมือชื่ออิเล็กทรอนิกส์ หลักฐานธุรกรรม และการใช้ผลงานอย่างถูกสิทธิ์",
    AIL: "ใช้ AI อย่างมีมนุษย์กำกับ ตรวจสอบความถูกต้อง ความลำเอียง ความเป็นส่วนตัว และความเสี่ยง",
    PRB: "วิเคราะห์ปัญหา เลือกเครื่องมือ ออกแบบ workflow ทดสอบ และพัฒนาทักษะอย่างต่อเนื่อง"
  },
  // กติกาการสุ่มตามไฟล์คลังข้อสอบ: ง่าย 4 / ปานกลาง 10 / ยาก 6 = 20 ข้อ
  difficultyQuota: { "ง่าย": 4, "ปานกลาง": 10, "ยาก": 6 },
  difficultyGuide: [
    { lv: "ง่าย", def: "ความรู้พื้นฐานหรือการตัดสินใจขั้นเดียว", secs: 45 },
    { lv: "ปานกลาง", def: "ประยุกต์ความรู้กับสถานการณ์งาน", secs: 75 },
    { lv: "ยาก", def: "วิเคราะห์ความเสี่ยงหลายเงื่อนไข", secs: 105 }
  ],
  samplingRules: [
    "กรองตามตำแหน่ง = ทุกตำแหน่ง + กลุ่มตำแหน่งที่สมัคร",
    "กรอง review_status = อนุมัติแล้ว และ expiry_date ยังไม่หมดอายุ",
    "สุ่ม 4 / 10 / 6 แยกทีละระดับแบบไม่ซ้ำ",
    "ตรวจหมวดไม่ให้กระจุกตัว และล็อกชุดข้อสอบเมื่อเริ่มสอบ",
    "ถ้าระดับใดมีข้อไม่พอ ให้หยุดและแจ้งแอดมิน"
  ],
  bank: [
    { id: "DL001", cat: "FND", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Digital Literacy หมายถึงข้อใดมากที่สุด", c: ["ความสามารถใช้ เข้าใจ ประเมิน และรับผิดชอบต่อเทคโนโลยีดิจิทัล", "การพิมพ์งานได้เร็วเพียงอย่างเดียว", "การมีอุปกรณ์รุ่นใหม่", "การใช้งานสื่อสังคมออนไลน์ทุกวัน"], a: 0, why: "ทักษะดิจิทัลครอบคลุมทั้งการใช้ การคิดเชิงวิพากษ์ ความปลอดภัย และความรับผิดชอบ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL002", cat: "FND", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ข้อใดเป็นเว็บเบราว์เซอร์", c: ["Microsoft Excel", "Google Chrome", "Adobe PDF", "Google Drive"], a: 1, why: "เว็บเบราว์เซอร์ใช้เปิดและโต้ตอบกับเว็บไซต์", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL003", cat: "FND", diff: "ง่าย", group: "เจ้าหน้าที่", q: "หากต้องการส่งเอกสารที่คงรูปแบบเดิมและผู้รับไม่ต้องแก้ไข ควรใช้ไฟล์ประเภทใด", c: ["XLSX", "PPTX", "PDF", "TXT"], a: 2, why: "PDF เหมาะกับการเผยแพร่เอกสารที่ต้องการคงรูปแบบ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL004", cat: "FND", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "สิ่งใดช่วยให้ค้นหาไฟล์ประชุมได้ง่ายที่สุด", c: ["ใช้ชื่อไฟล์ว่า final ทุกครั้ง", "เก็บทุกไฟล์ไว้บน Desktop", "ส่งไฟล์ให้ตนเองทางแชต", "ตั้งชื่อไฟล์ให้มีวันที่ หัวข้อ และเวอร์ชันอย่างสม่ำเสมอ"], a: 3, why: "โครงสร้างชื่อไฟล์ที่สม่ำเสมอช่วยค้นหาและควบคุมเวอร์ชัน", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL005", cat: "FND", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "การซิงก์ไฟล์กับคลาวด์แตกต่างจากการสำรองข้อมูลอย่างไร", c: ["การซิงก์อาจส่งต่อการลบหรือความเสียหายไปทุกอุปกรณ์ จึงไม่แทนการสำรองข้อมูลทั้งหมด", "การซิงก์ปลอดภัยกว่าการสำรองเสมอ", "การสำรองข้อมูลทำได้เฉพาะออฟไลน์", "ทั้งสองอย่างเหมือนกันทุกกรณี"], a: 0, why: "ไฟล์ที่ซิงก์อาจถูกลบหรือเข้ารหัสพร้อมกัน จึงควรมีสำเนากู้คืนแยกต่างหาก", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL006", cat: "FND", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "พบไฟล์ชื่อ รายงาน_final_final2.xlsx หลายชุด ควรปรับวิธีทำงานอย่างไร", c: ["ลบทุกไฟล์แล้วเริ่มใหม่", "กำหนดรูปแบบชื่อ เวอร์ชัน และแหล่งเก็บกลางเพียงแห่งเดียว", "เปลี่ยนนามสกุลไฟล์เป็น PDF", "ส่งไฟล์ทั้งหมดให้ทุกคนเลือกเอง"], a: 1, why: "การกำกับเวอร์ชันและแหล่งเก็บกลางลดความสับสน", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL007", cat: "FND", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ต้องรวบรวมข้อมูลตัวเลข 500 รายการและคำนวณผลรวม ควรเลือกเครื่องมือใด", c: ["โปรแกรมวาดภาพ", "โปรแกรมตัดต่อวิดีโอ", "โปรแกรมตารางคำนวณ", "โปรแกรมนำเสนอ"], a: 2, why: "ตารางคำนวณรองรับข้อมูลแบบตาราง สูตร และการตรวจสอบตัวเลข", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL008", cat: "FND", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ผู้เข้าร่วมประชุมบางคนแก้ไขไฟล์ร่วมกันไม่ได้ สาเหตุแรกที่ควรตรวจคืออะไร", c: ["สีของไอคอนไฟล์", "ความยาวชื่อการประชุม", "จำนวนหน้าของเอกสาร", "สิทธิ์การเข้าถึงและบัญชีที่ใช้เปิดไฟล์"], a: 3, why: "ปัญหาการทำงานร่วมกันมักเกิดจากสิทธิ์หรือบัญชีไม่ตรง", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL009", cat: "FND", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องแจกเอกสารให้นักศึกษาอ่านได้บนหลายอุปกรณ์และไม่ต้องแก้ไข ควรทำอย่างไร", c: ["ส่งออกเป็น PDF ที่อ่านข้อความค้นหาได้และตรวจการเข้าถึง", "ถ่ายภาพทุกหน้าเป็นรูปความละเอียดต่ำ", "ส่งไฟล์เฉพาะรูปแบบโปรแกรมต้นฉบับ", "บีบอัดเป็นไฟล์ที่ต้องติดตั้งโปรแกรมเฉพาะ"], a: 0, why: "PDF แบบมีข้อความและเข้าถึงได้รองรับผู้ใช้และอุปกรณ์หลากหลายกว่า", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL010", cat: "FND", diff: "ยาก", group: "ทุกตำแหน่ง", q: "ทีมแก้ไฟล์เดียวกันแบบออฟไลน์หลายคนและเกิดข้อมูลชนกัน วิธีใดลดความเสี่ยงได้ดีที่สุด", c: ["ให้ทุกคนเปลี่ยนชื่อไฟล์ตามใจ", "ใช้เอกสารร่วมบนระบบกลาง กำหนดสิทธิ์ และเปิดประวัติเวอร์ชัน", "รวมไฟล์ด้วยการคัดลอกทับเวอร์ชันล่าสุด", "ส่งไฟล์วนในกลุ่มแชตจนกว่าจะครบ"], a: 1, why: "แหล่งข้อมูลกลางและประวัติเวอร์ชันช่วยป้องกันการเขียนทับและย้อนคืนได้", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL011", cat: "FND", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "หน่วยงานย้ายไฟล์ขึ้นคลาวด์ แต่ต้องลดทั้งไฟล์ซ้ำและการเปิดเผยเกินจำเป็น ควรเริ่มอย่างไร", c: ["ให้ทุกคนเป็นผู้แก้ไขทุกโฟลเดอร์", "อัปโหลดทุกอย่างไว้โฟลเดอร์เดียว", "จำแนกข้อมูล ออกแบบโฟลเดอร์ กำหนดเจ้าของ และใช้สิทธิ์ตามบทบาท", "ตั้งลิงก์สาธารณะเพื่อให้เข้าถึงง่าย"], a: 2, why: "การจำแนกข้อมูลและกำหนดเจ้าของเป็นฐานของโครงสร้างและสิทธิ์ที่เหมาะสม", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL012", cat: "FND", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "เอกสารการสอนมีลิงก์ภายนอกจำนวนมาก วิธีใดช่วยให้ใช้งานระยะยาวได้ดีที่สุด", c: ["ใช้ข้อความว่า คลิกที่นี่ ทุกลิงก์", "แปลงทุกลิงก์เป็น QR โดยไม่ใส่คำอธิบาย", "ตัดชื่อผู้เขียนและวันที่ออก", "ใช้ชื่อแหล่งข้อมูลที่ชัด ตรวจลิงก์เป็นระยะ และมีข้อมูลสำรองที่ได้รับอนุญาต"], a: 3, why: "บริบทของลิงก์และการตรวจสม่ำเสมอช่วยทั้งการเข้าถึงและความน่าเชื่อถือ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL013", cat: "PRD", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "หากต้องการคำนวณยอดรวมจากข้อมูลหลายแถว ควรใช้เครื่องมือใด", c: ["โปรแกรมตารางคำนวณ", "โปรแกรมนำเสนอ", "โปรแกรมอ่าน PDF", "โปรแกรมวาดภาพ"], a: 0, why: "ตารางคำนวณออกแบบมาเพื่อจัดการและคำนวณข้อมูล", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL014", cat: "PRD", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ฟังก์ชันใดใช้แสดงเฉพาะแถวที่ตรงเงื่อนไขในตาราง", c: ["Spell Check", "Filter", "Slide Show", "Track Changes"], a: 1, why: "Filter ใช้ซ่อนแถวที่ไม่ตรงเงื่อนไขชั่วคราว", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL015", cat: "PRD", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ต้องส่งจดหมายรูปแบบเดียวกันให้ผู้รับหลายรายโดยเปลี่ยนชื่อและหน่วยงาน ควรใช้แนวทางใด", c: ["บันทึกเป็นรูปภาพ", "สร้างหนึ่งสไลด์ต่อคน", "Mail Merge", "คัดลอกด้วยมือทุกฉบับ"], a: 2, why: "Mail Merge ผสานแม่แบบกับแหล่งข้อมูลผู้รับได้", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL016", cat: "PRD", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "คำเชิญประชุมที่ดีควรมีข้อมูลใดอย่างน้อย", c: ["เฉพาะชื่อผู้จัด", "เฉพาะไฟล์แนบ", "เฉพาะสีปฏิทิน", "หัวข้อ วันเวลา สถานที่หรือลิงก์ และวาระ"], a: 3, why: "ข้อมูลหลักช่วยให้ผู้เข้าร่วมเตรียมตัวและเข้าร่วมได้ถูกต้อง", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL017", cat: "PRD", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "ตารางยอดขายมีหัวคอลัมน์และข้อมูล 1,000 แถว ต้องการเรียงยอดจากมากไปน้อยโดยไม่แยกแถว ควรทำอย่างไร", c: ["เลือกทั้งตารางแล้ว Sort ตามคอลัมน์ยอดขาย", "เรียงเฉพาะคอลัมน์ยอดขาย", "คัดลอกยอดไปเอกสาร Word", "เปลี่ยนสีเซลล์ตามยอด"], a: 0, why: "ต้องเรียงทั้งตารางเพื่อรักษาความสัมพันธ์ระหว่างแถว", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL018", cat: "PRD", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "สูตรคำนวณอัตราส่วนให้ข้อผิดพลาดเมื่อค่าตัวหารเป็นศูนย์ ควรจัดการอย่างไร", c: ["ซ่อนคอลัมน์ผลลัพธ์", "ตรวจข้อมูลและใช้เงื่อนไขรองรับกรณีตัวหารเป็นศูนย์", "เปลี่ยนศูนย์เป็นข้อความทุกแถว", "ปัดทศนิยมเพิ่ม"], a: 1, why: "ควรแก้ทั้งคุณภาพข้อมูลและตรรกะของสูตร ไม่ใช่ซ่อนข้อผิดพลาด", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL019", cat: "PRD", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ต้องจำกัดให้ช่องสถานะรับเฉพาะ รอดำเนินการ กำลังทำ และเสร็จแล้ว ควรใช้สิ่งใด", c: ["เพิ่มสีด้วยมือ", "รวมเซลล์", "Data Validation แบบรายการ", "แทรกรูปภาพ"], a: 2, why: "Data Validation ลดค่าที่สะกดต่างกันและช่วยควบคุมคุณภาพข้อมูล", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL020", cat: "PRD", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "มีการแก้กำหนดการประชุมหลังส่งคำเชิญแล้ว วิธีใดเหมาะที่สุด", c: ["สร้างเหตุการณ์ใหม่โดยไม่ยกเลิกของเดิม", "ส่งข้อความส่วนตัวทีละคนเท่านั้น", "ลบปฏิทินทั้งหมด", "แก้เหตุการณ์เดิมและส่งอัปเดตให้ผู้เข้าร่วม"], a: 3, why: "การอัปเดตเหตุการณ์เดิมลดรายการซ้ำและทำให้ทุกคนเห็นข้อมูลล่าสุด", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL021", cat: "PRD", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องการเก็บงานนักศึกษาโดยไม่ให้นักศึกษาเห็นไฟล์ของกันและกัน ควรตั้งค่าอย่างไร", c: ["ใช้พื้นที่ส่งงานที่แยกสิทธิ์รายบุคคลหรือระบบ LMS", "ใช้โฟลเดอร์ที่ทุกคนเป็น Editor", "ให้ส่งในห้องแชตสาธารณะ", "สร้างลิงก์ Anyone with the link"], a: 0, why: "พื้นที่ส่งงานควรแยกสิทธิ์เพื่อคุ้มครองงานและข้อมูลนักศึกษา", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL022", cat: "PRD", diff: "ยาก", group: "ทุกตำแหน่ง", q: "Dashboard สรุปจำนวนผู้สมัครไม่ตรงกับข้อมูลดิบ ควรตรวจตามลำดับใด", c: ["เปลี่ยนชนิดกราฟก่อน", "นิยามตัวชี้วัด ช่วงข้อมูล ตัวกรอง สูตร และรายการซ้ำ", "เพิ่มสีให้ตัวเลขสำคัญ", "คัดลอกค่าจาก Dashboard ทับข้อมูลดิบ"], a: 1, why: "ความคลาดเคลื่อนควรตรวจจากนิยามและสายการคำนวณก่อนการนำเสนอ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL023", cat: "PRD", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "รายงานประชุมถูกแก้หลายคนและต้องทราบว่าใครแก้อะไร ควรใช้ชุดการตั้งค่าใด", c: ["ไฟล์แนบทางอีเมลหลายสำเนา", "ไฟล์ PDF ที่ทุกคนเขียนทับ", "เอกสารร่วมที่มีสิทธิ์ตามบทบาท ประวัติเวอร์ชัน และโหมดเสนอแนะ", "ลิงก์สาธารณะแบบแก้ไขได้"], a: 2, why: "ประวัติเวอร์ชันและโหมดเสนอแนะสร้างร่องรอยการแก้ไขที่ตรวจสอบได้", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL024", cat: "PRD", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องเปรียบเทียบผลก่อนเรียนและหลังเรียนของนักศึกษากลุ่มเดิม วิธีเตรียมข้อมูลใดเหมาะที่สุด", c: ["เก็บเฉพาะคะแนนเฉลี่ยรวม", "เรียงชื่อแล้วถือว่าแถวตรงกันเสมอ", "ลบผู้ที่คะแนนไม่เปลี่ยน", "ใช้รหัสผู้เรียนเดียวกัน แยกตัวแปรก่อน–หลัง และตรวจค่าขาดหาย"], a: 3, why: "รหัสเชื่อมโยงและการตรวจคุณภาพจำเป็นต่อการเปรียบเทียบแบบจับคู่", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S02", url: "https://www.dga.or.th/wp-content/uploads/2025/01/%E0%B8%AA%E0%B8%84%E0%B8%8A.-PPT_%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A1%E0%B8%99%E0%B8%B2%E0%B8%AA%E0%B8%96%E0%B8%B2%E0%B8%99%E0%B8%A0%E0%B8%B2%E0%B8%9E%E0%B8%84%E0%B8%A7%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%A3%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%A3%E0%B8%B1%E0%B8%90%E0%B8%9A%E0%B8%B2%E0%B8%A5%E0%B8%94%E0%B8%B4%E0%B8%88%E0%B8%B4%E0%B8%97%E0%B8%B1%E0%B8%A5%E0%B9%84%E0%B8%97%E0%B8%A2_2024-01-20.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL025", cat: "INF", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ข้อใดเป็นข้อเท็จจริงมากที่สุด", c: ["มหาวิทยาลัยประกาศกำหนดการบนเว็บไซต์ทางการเมื่อวันที่ระบุ", "ระบบใหม่นี้ใช้ง่ายที่สุด", "หลักสูตรนี้น่าสนใจมาก", "ทุกคนชอบการเรียนออนไลน์"], a: 0, why: "ข้อเท็จจริงตรวจสอบย้อนกลับได้ ส่วนข้อความอื่นเป็นความเห็นหรือการเหมารวม", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL026", cat: "INF", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ก่อนแชร์ข่าวสาร สิ่งแรกที่ควรตรวจคืออะไร", c: ["จำนวนอีโมจิ", "แหล่งที่มา วันที่ และหลักฐานสนับสนุน", "จำนวนครั้งที่ถูกแชร์", "ชื่อไฟล์รูปภาพ"], a: 1, why: "ความนิยมไม่ยืนยันความถูกต้อง ต้องตรวจแหล่งและหลักฐาน", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL027", cat: "INF", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ต้องค้นเอกสารที่มีวลีตรงตัว ควรใช้วิธีใด", c: ["พิมพ์คำทั้งหมดโดยไม่เว้นวรรค", "ค้นจากรูปภาพเท่านั้น", "ใส่วลีในเครื่องหมายอัญประกาศ", "เพิ่มคำว่า viral"], a: 2, why: "เครื่องหมายอัญประกาศช่วยค้นวลีตรงตัวในเครื่องมือค้นหาทั่วไป", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL028", cat: "INF", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "แหล่งใดเหมาะที่สุดสำหรับยืนยันวันประชุมอย่างเป็นทางการ", c: ["ข้อความส่งต่อที่ไม่ทราบผู้ส่ง", "โพสต์ส่วนตัวของผู้เข้าร่วม", "ความจำของเพื่อนร่วมงาน", "หนังสือหรือปฏิทินที่เจ้าของเรื่องรับรอง"], a: 3, why: "ข้อมูลทางการควรยืนยันจากเจ้าของเรื่องหรือเอกสารที่รับรอง", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL029", cat: "INF", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "บทความอ้างงานวิจัยแต่ไม่มีชื่อผู้วิจัย ปี หรือลิงก์ต้นฉบับ ควรทำอย่างไร", c: ["ค้นหางานต้นฉบับและตรวจว่าข้อสรุปตรงกับหลักฐาน", "อ้างบทความนั้นทันที", "ใช้จำนวนผู้ติดตามผู้เขียนแทน", "ตัดคำว่า งานวิจัย ออกแล้วแชร์"], a: 0, why: "การตรวจแหล่งต้นฉบับป้องกันการบิดความหมายและการอ้างอิงผิด", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL030", cat: "INF", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "กราฟเริ่มแกนตั้งที่ 95 ทำให้ความต่าง 95 กับ 100 ดูใหญ่มาก ควรตีความอย่างไร", c: ["เชื่อภาพกราฟโดยไม่ดูตัวเลข", "ตรวจช่วงแกนและดูค่าจริงก่อนสรุปขนาดความแตกต่าง", "ถือว่าค่าต่างกัน 100%", "ลบแกนออกเพื่อให้อ่านง่าย"], a: 1, why: "แกนที่ตัดช่วงอาจขยายความแตกต่างทางสายตา", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL031", cat: "INF", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ข้อมูลรายชื่อมีคนเดียวกันซ้ำเพราะสะกดต่างกันเล็กน้อย ควรทำอะไร", c: ["นับทุกแถวเป็นคนใหม่", "เรียงตามสีเซลล์", "กำหนดรหัสเฉพาะและกติกาทำความสะอาดก่อนนับ", "ลบชื่อที่สั้นกว่า"], a: 2, why: "รหัสเฉพาะและกติกาที่ตรวจสอบได้ช่วยลดการรวม/แยกคนผิด", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL032", cat: "INF", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ได้รับตัวเลขจากสองฝ่ายไม่ตรงกัน วิธีประสานงานที่เหมาะที่สุดคืออะไร", c: ["เลือกตัวเลขที่มากกว่า", "เฉลี่ยสองค่าโดยไม่ตรวจ", "ใช้ตัวเลขที่ส่งมาก่อน", "เทียบนิยาม ช่วงเวลา แหล่งข้อมูล และเวลาที่ดึงข้อมูลร่วมกัน"], a: 3, why: "ความต่างมักมาจากนิยาม เวลา หรือแหล่งข้อมูล จึงต้องปรับฐานให้ตรงกัน", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL033", cat: "INF", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "นักศึกษานำภาพจากเว็บไซต์มาใส่รายงานโดยไม่มีที่มา ควรแนะนำอย่างไร", c: ["ตรวจสิทธิ์การใช้และระบุแหล่งที่มาให้ครบ", "ใช้ได้เสมอถ้าเพื่อการศึกษา", "ครอปโลโก้ออกแล้วใช้ได้", "ใส่คำว่า จากอินเทอร์เน็ต ก็พอ"], a: 0, why: "การใช้เพื่อการศึกษาไม่ได้ลบข้อกำหนดเรื่องสิทธิ์และการอ้างอิง", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL034", cat: "INF", diff: "ยาก", group: "ทุกตำแหน่ง", q: "ข่าวเดียวกันปรากฏในหลายเว็บไซต์แต่ทั้งหมดคัดลอกจากแหล่งเดียว วิธีตรวจสอบที่ถูกต้องคืออะไร", c: ["นับจำนวนเว็บไซต์เป็นจำนวนหลักฐาน", "ติดตามไปยังแหล่งต้นทางและหาหลักฐานอิสระเพิ่มเติม", "เชื่อเว็บที่ออกแบบสวยที่สุด", "เลือกข้อความที่ตรงกับความเห็นของตน"], a: 1, why: "หลายสำเนาจากต้นทางเดียวไม่ใช่หลักฐานอิสระหลายชิ้น", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL035", cat: "INF", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "ต้องสรุปผลสำรวจที่มีผู้ตอบเพียง 12% ของกลุ่มเป้าหมาย ควรรายงานอย่างไร", c: ["รายงานเป็นตัวแทนทั้งหมดโดยไม่ระบุข้อจำกัด", "เพิ่มน้ำหนักทุกคนเท่ากันโดยไม่มีเหตุผล", "แสดงอัตราตอบ ลักษณะผู้ตอบ และข้อจำกัดก่อนขยายผล", "ตัดผู้ตอบที่เห็นต่างออก"], a: 2, why: "อัตราตอบต่ำอาจเกิดอคติจากการไม่ตอบ จึงต้องเปิดเผยข้อจำกัด", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL036", cat: "INF", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "บทความจากวารสารดูน่าเชื่อถือ แต่ข้อสรุปอ้างเกินข้อมูลที่ศึกษา ควรประเมินอย่างไร", c: ["ดูเฉพาะชื่อวารสาร", "ดูจำนวนหน้า", "เชื่อบทคัดย่อโดยไม่อ่านผล", "ตรวจวิธีวิจัย กลุ่มตัวอย่าง ผลลัพธ์จริง และขอบเขตการสรุป"], a: 3, why: "ความน่าเชื่อถือของแหล่งไม่แทนการประเมินวิธีและความสอดคล้องของข้อสรุป", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL037", cat: "COM", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "หัวเรื่องอีเมลที่ดีควรเป็นอย่างไร", c: ["สั้น ชัด และบอกสิ่งที่ต้องดำเนินการ", "เว้นว่างไว้", "ใช้คำว่า ด่วน ทุกฉบับ", "ใส่อีโมจิหลายตัวแทนเนื้อหา"], a: 0, why: "หัวเรื่องที่ชัดช่วยให้ผู้รับจัดลำดับและค้นหาได้", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL038", cat: "COM", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "BCC เหมาะกับกรณีใด", c: ["ต้องการให้ทุกคนตอบกลับทั้งหมด", "ส่งถึงผู้รับจำนวนมากโดยไม่เปิดเผยอีเมลของกันและกัน", "ต้องการแก้ไฟล์ร่วมกัน", "ต้องการเพิ่มลายเซ็น"], a: 1, why: "BCC ซ่อนรายชื่อผู้รับจากผู้รับรายอื่น", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL039", cat: "COM", diff: "ง่าย", group: "เจ้าหน้าที่", q: "เมื่อส่งไฟล์แนบให้ผู้บริหาร ควรทำสิ่งใด", c: ["แนบไฟล์ชื่อ document1 โดยไม่เปิดตรวจ", "ส่งลิงก์สาธารณะแบบแก้ไขได้", "ตั้งชื่อไฟล์ชัด ตรวจไฟล์ และกล่าวถึงไฟล์แนบในข้อความ", "บีบอัดด้วยรหัสผ่านแล้วส่งรหัสในหัวเรื่อง"], a: 2, why: "การตรวจไฟล์ ชื่อ และบริบทลดการส่งผิดและช่วยผู้รับใช้งาน", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL040", cat: "COM", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "ประชุมออนไลน์มีเสียงสะท้อน วิธีแก้เบื้องต้นคืออะไร", c: ["เปิดลำโพงทุกเครื่อง", "แชร์หน้าจอซ้ำ", "เพิ่มความละเอียดกล้อง", "ปิดไมโครโฟนของอุปกรณ์ที่ไม่ได้ใช้หรือใช้ชุดหูฟัง"], a: 3, why: "เสียงสะท้อนมักเกิดจากเสียงลำโพงย้อนเข้าไมโครโฟนอีกเครื่อง", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL041", cat: "COM", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "เรื่องเร่งด่วนและมีผลต่อหลายฝ่าย ควรสื่อสารอย่างไร", c: ["ใช้ช่องทางที่ตกลงกัน ระบุผู้รับผิดชอบ เวลา และบันทึกการยืนยัน", "โพสต์ในช่องส่วนตัวที่ไม่มีผู้เกี่ยวข้อง", "ส่งข้อความสั้นว่า ช่วยดูด้วย", "ใช้หลายช่องทางโดยข้อมูลไม่ตรงกัน"], a: 0, why: "การสื่อสารเหตุเร่งด่วนต้องชัดทั้งผู้รับผิดชอบ กำหนดเวลา และหลักฐานการรับทราบ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL042", cat: "COM", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "ได้รับข้อความตำหนิรุนแรงในกลุ่มงาน วิธีตอบที่เหมาะสมคืออะไร", c: ["ตอบโต้ทันทีด้วยถ้อยคำเดียวกัน", "แยกข้อเท็จจริง ตอบอย่างสุภาพ และย้ายประเด็นละเอียดไปช่องทางเหมาะสม", "ส่งต่อออกนอกกลุ่ม", "ลบหลักฐานทั้งหมด"], a: 1, why: "การลดความขัดแย้งควรรักษาข้อเท็จจริง น้ำเสียง และบริบท", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL043", cat: "COM", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ต้องส่งข้อมูลส่วนบุคคลให้ผู้รับภายในองค์กร วิธีใดปลอดภัยกว่า", c: ["ส่งเข้ากลุ่มแชตใหญ่", "สร้างลิงก์ Anyone with the link", "ยืนยันผู้รับ ใช้ช่องทางที่อนุมัติ และจำกัดสิทธิ์เฉพาะที่จำเป็น", "ใช้บัญชีส่วนตัวเพราะสะดวก"], a: 2, why: "ข้อมูลส่วนบุคคลควรส่งตามความจำเป็นและผ่านช่องทางควบคุมได้", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL044", cat: "COM", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "มีการประชุมข้ามเขตเวลา วิธีลดความผิดพลาดคืออะไร", c: ["พิมพ์เวลาอย่างเดียวในแชต", "ส่งภาพนาฬิกา", "ใช้คำว่า ช่วงบ่าย โดยไม่ระบุประเทศ", "ส่งคำเชิญปฏิทินที่ระบุเขตเวลาและให้ระบบแปลงอัตโนมัติ"], a: 3, why: "ปฏิทินที่กำหนดเขตเวลาชัดช่วยลดการแปลงเวลาผิด", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL045", cat: "COM", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "นักศึกษาถามคะแนนในกลุ่มชั้นเรียน ควรตอบอย่างไร", c: ["ย้ายไปช่องทางส่วนตัวที่ยืนยันตัวตนได้", "โพสต์คะแนนทุกคนเพื่อความโปร่งใส", "ส่งภาพหน้าจอคะแนนรวม", "ให้เพื่อนนักศึกษาตอบแทน"], a: 0, why: "คะแนนเป็นข้อมูลส่วนบุคคลและควรสื่อสารกับเจ้าของข้อมูลโดยตรง", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL046", cat: "COM", diff: "ยาก", group: "ทุกตำแหน่ง", q: "โครงการใช้ทั้งอีเมล แชต และระบบงานจนข้อมูลไม่ตรงกัน ควรออกแบบการสื่อสารใหม่อย่างไร", c: ["เพิ่มช่องทางใหม่อีกหนึ่งช่อง", "กำหนดช่องทางหลักตามประเภทเรื่อง เจ้าของข้อมูล และกติกาบันทึกมติ", "ให้แต่ละคนเลือกช่องทางเอง", "คัดลอกทุกข้อความไปทุกระบบ"], a: 1, why: "การกำกับช่องทางและแหล่งข้อมูลหลักลดความคลาดเคลื่อนและภาระซ้ำ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL047", cat: "COM", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "ต้องแจ้งเหตุระบบล่ม แต่ยังไม่ทราบสาเหตุแน่ชัด ข้อความใดมีคุณภาพที่สุด", c: ["ประกาศสาเหตุที่คาดไว้เป็นข้อเท็จจริง", "บอกว่าไม่มีอะไรต้องกังวลโดยไม่มีข้อมูล", "แจ้งสิ่งที่ทราบ ผลกระทบ การแก้ชั่วคราว เวลาอัปเดตครั้งถัดไป และหลีกเลี่ยงการคาดเดา", "รอจนแก้เสร็จแล้วค่อยแจ้ง"], a: 2, why: "การสื่อสารเหตุขัดข้องต้องโปร่งใสเรื่องความไม่แน่นอนและรอบอัปเดต", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL048", cat: "COM", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องบันทึกการสอนออนไลน์เพื่อทบทวนภายหลัง ควรทำอย่างไร", c: ["บันทึกและเผยแพร่สาธารณะทันที", "ให้ผู้เรียนคนหนึ่งตัดสินใจแทนทั้งหมด", "บันทึกเฉพาะเสียงจึงไม่ต้องแจ้ง", "แจ้งวัตถุประสงค์ ผู้เข้าถึง ระยะเวลาเก็บ และจัดทางเลือกที่เหมาะสมก่อนบันทึก"], a: 3, why: "การบันทึกเกี่ยวข้องกับข้อมูลและสิทธิของผู้เข้าร่วม ต้องกำหนดวัตถุประสงค์และการเข้าถึง", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL049", cat: "SEC", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Phishing คืออะไร", c: ["การหลอกให้เปิดเผยข้อมูลหรือทำสิ่งที่เป็นอันตรายโดยปลอมเป็นแหล่งน่าเชื่อถือ", "การบีบอัดไฟล์", "การสำรองข้อมูล", "การอัปเดตระบบ"], a: 0, why: "ฟิชชิงอาศัยการหลอกลวงเพื่อขโมยข้อมูลหรือติดตั้งอันตราย", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL050", cat: "SEC", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "MFA เพิ่มความปลอดภัยอย่างไร", c: ["ทำให้ไม่ต้องใช้บัญชีผู้ใช้", "ต้องใช้หลักฐานยืนยันมากกว่ารหัสผ่านเพียงอย่างเดียว", "เข้ารหัสไฟล์ทุกชนิดอัตโนมัติ", "ลบมัลแวร์ออกจากเครื่อง"], a: 1, why: "MFA ลดความเสี่ยงเมื่อรหัสผ่านถูกขโมย", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL051", cat: "SEC", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ข้อใดเป็นแนวทางรหัสผ่านที่เหมาะสม", c: ["ใช้รหัสเดียวทุกระบบ", "ใช้ชื่อหน่วยงานตามด้วย 123", "ใช้รหัสผ่านยาว ไม่ซ้ำ และเก็บใน password manager ที่เชื่อถือได้", "เขียนรหัสไว้ใต้แป้นพิมพ์"], a: 2, why: "รหัสยาวและไม่ซ้ำจำกัดผลกระทบจากการรั่วไหลหนึ่งระบบ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL052", cat: "SEC", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "ได้รับไฟล์แนบไม่คาดคิดจากชื่อผู้บริหาร สิ่งแรกที่ควรทำคืออะไร", c: ["เปิดทันทีเพราะชื่อผู้ส่งคุ้นเคย", "ส่งต่อให้ทุกคนช่วยเปิด", "ปิดโปรแกรมป้องกันไวรัส", "ตรวจผู้ส่งและยืนยันผ่านช่องทางอื่นก่อนเปิด"], a: 3, why: "บัญชีหรือชื่อผู้ส่งอาจถูกปลอม จึงควรยืนยันก่อน", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL053", cat: "SEC", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "หน้าเข้าสู่ระบบเปิดจากลิงก์ในอีเมลและโดเมนสะกดต่างไปหนึ่งตัว ควรทำอย่างไร", c: ["ปิดหน้าและเข้าเว็บไซต์จากบุ๊กมาร์กหรือพิมพ์ที่อยู่ทางการเอง", "กรอกรหัสผ่านแล้วค่อยตรวจ", "ดูเฉพาะโลโก้", "กดอนุญาตการแจ้งเตือน"], a: 0, why: "โดเมนคล้ายเป็นสัญญาณฟิชชิง ควรเข้าสู่บริการจากเส้นทางที่เชื่อถือได้", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL054", cat: "SEC", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "โทรศัพท์แจ้งเตือนคำขอ MFA ที่ตนไม่ได้เริ่มหลายครั้ง ควรทำอย่างไร", c: ["กดยอมรับเพื่อหยุดแจ้งเตือน", "ปฏิเสธคำขอ เปลี่ยนรหัสผ่าน และรายงานทีมที่รับผิดชอบ", "ปิดเสียงแล้วไม่ต้องทำอะไร", "ส่งรหัส OTP ให้ผู้โทร"], a: 1, why: "คำขอที่ไม่ได้เริ่มอาจหมายถึงรหัสผ่านรั่วและเป็น MFA fatigue attack", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL055", cat: "SEC", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "คอมพิวเตอร์แจ้งให้อัปเดตจากป๊อปอัปเว็บไซต์ที่ไม่รู้จัก ควรทำอย่างไร", c: ["ดาวน์โหลดจากป๊อปอัป", "ปิดระบบป้องกันเพื่อให้อัปเดตได้", "ปิดป๊อปอัปและอัปเดตผ่านระบบหรือศูนย์ซอฟต์แวร์ทางการ", "ส่งลิงก์ให้เพื่อนร่วมงาน"], a: 2, why: "การอัปเดตควรมาจากช่องทางที่เชื่อถือได้ ไม่ใช่ป๊อปอัปสุ่ม", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL056", cat: "SEC", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ต้องส่งเอกสารสำคัญให้บุคคลภายนอก วิธีใดลดความเสี่ยงได้ดีที่สุด", c: ["แนบในกลุ่มแชตเปิด", "ใช้ลิงก์สาธารณะถาวร", "ส่งจากบัญชีส่วนตัว", "ใช้ลิงก์จำกัดผู้รับ กำหนดวันหมดอายุ และยืนยันตัวตนผู้รับ"], a: 3, why: "การจำกัดผู้รับและอายุลิงก์ลดการเข้าถึงเกินความจำเป็น", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL057", cat: "SEC", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "นักศึกษาส่งไฟล์ที่ระบบเตือนว่าอาจมีมัลแวร์ ควรทำอย่างไร", c: ["ไม่เปิดไฟล์ แยกกัก และให้ส่งใหม่ผ่านช่องทางที่กำหนดพร้อมรายงานเหตุ", "ปิดระบบเตือนแล้วเปิด", "เปลี่ยนนามสกุลไฟล์", "ส่งต่อให้นักศึกษาคนอื่นทดสอบ"], a: 0, why: "คำเตือนต้องได้รับการจัดการโดยไม่เพิ่มการแพร่กระจาย", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL058", cat: "SEC", diff: "ยาก", group: "ทุกตำแหน่ง", q: "พบไฟล์จำนวนมากถูกเปลี่ยนนามสกุลและเปิดไม่ได้ ควรทำสิ่งใดก่อน", c: ["จ่ายเงินตามข้อความทันที", "ตัดการเชื่อมต่อเครือข่าย แจ้งทีมตอบสนองเหตุ และรักษาหลักฐาน", "ลบทุกไฟล์และติดตั้งใหม่เอง", "เชื่อมไดรฟ์สำรองเพื่อทดสอบ"], a: 1, why: "อาการอาจเป็น ransomware ควรจำกัดการแพร่กระจายและใช้กระบวนการตอบสนองเหตุ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL059", cat: "SEC", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "ทีมใช้บัญชีกลางบัญชีเดียวเพื่ออนุมัติเอกสาร ปัญหาหลักคืออะไร", c: ["ประหยัดรหัสผ่านมากเกินไป", "หน้าจอเข้าสู่ระบบจะช้าลง", "ไม่สามารถระบุตัวผู้กระทำและเพิกถอนสิทธิ์รายบุคคลได้", "ชื่อบัญชีสั้นเกินไป"], a: 2, why: "บัญชีร่วมทำลายความรับผิดชอบและการตรวจสอบย้อนหลัง", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL060", cat: "SEC", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องใช้บริการออนไลน์ใหม่กับข้อมูลวิจัยที่ยังไม่เผยแพร่ ควรประเมินอะไรก่อน", c: ["จำนวนผู้ติดตามของบริการ", "ความสวยของหน้าเว็บ", "มีทดลองใช้ฟรีหรือไม่", "ประเภทข้อมูล เงื่อนไขบริการ ที่เก็บข้อมูล สิทธิ์เข้าถึง และทางเลือกที่องค์กรอนุมัติ"], a: 3, why: "ข้อมูลอ่อนไหวต้องประเมินทั้งการกำกับและความปลอดภัยก่อนนำขึ้นบริการ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S04", url: "https://www.cisa.gov/secure-our-world", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL061", cat: "PRI", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ข้อใดเป็นข้อมูลส่วนบุคคล", c: ["ข้อมูลที่ทำให้ระบุตัวบุคคลได้โดยตรงหรือโดยอ้อม", "ชื่ออาคารที่ไม่มีผู้เกี่ยวข้อง", "อุณหภูมิรายวันแบบไม่ผูกกับบุคคล", "จำนวนเก้าอี้ในห้อง"], a: 0, why: "ข้อมูลส่วนบุคคลเชื่อมโยงกลับไปยังบุคคลได้", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL062", cat: "PRI", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "หลักการเก็บข้อมูลเท่าที่จำเป็นหมายถึงอะไร", c: ["เก็บทุกอย่างเผื่อใช้ในอนาคต", "เก็บเฉพาะข้อมูลที่จำเป็นต่อวัตถุประสงค์ที่กำหนด", "เก็บข้อมูลโดยไม่บอกวัตถุประสงค์", "ส่งข้อมูลให้ทุกฝ่ายสำรองไว้"], a: 1, why: "Data minimization ลดความเสี่ยงและจำกัดการใช้เกินวัตถุประสงค์", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL063", cat: "PRI", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ได้รับไฟล์รายชื่อที่ไม่เกี่ยวกับงานของตน ควรทำอย่างไร", c: ["เก็บไว้เผื่อใช้", "อัปโหลดไว้บนคลาวด์ส่วนตัว", "ไม่เปิดหรือส่งต่อ และแจ้งผู้ส่งตามช่องทางที่กำหนด", "ส่งให้เพื่อนถามว่าเป็นของใคร"], a: 2, why: "ควรจำกัดการเข้าถึงและรายงานการส่งผิดโดยไม่ขยายการเปิดเผย", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL064", cat: "PRI", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "การส่งอีเมลถึงผู้รับภายนอกจำนวนมากควรใช้วิธีใดเพื่อลดการเปิดเผยอีเมล", c: ["ใส่ทุกคนใน To", "แนบรายชื่อทั้งหมด", "โพสต์รายชื่อก่อนส่ง", "ใช้ BCC หรือระบบส่งที่ซ่อนรายชื่อผู้รับ"], a: 3, why: "การซ่อนรายชื่อผู้รับช่วยป้องกันการเปิดเผยข้อมูลติดต่อโดยไม่จำเป็น", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL065", cat: "PRI", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "แบบฟอร์มกิจกรรมขอเลขบัตรประชาชนทั้งที่ใช้เพียงยืนยันจำนวนผู้เข้าร่วม ควรทำอย่างไร", c: ["ทบทวนและตัดข้อมูลที่ไม่จำเป็นออก", "เก็บไว้เพราะแบบฟอร์มทำได้", "เพิ่มสำเนาบัตรประชาชน", "เผยแพร่รายชื่อเพื่อความโปร่งใส"], a: 0, why: "วัตถุประสงค์ไม่รองรับการเก็บเลขบัตร จึงควรลดข้อมูล", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL066", cat: "PRI", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "ต้องใช้ข้อมูลเดิมเพื่อวัตถุประสงค์ใหม่ที่ผู้ให้ข้อมูลไม่คาดหมาย ควรทำอย่างไร", c: ["ใช้ได้ทันทีเพราะข้อมูลอยู่ในองค์กร", "ให้ผู้รับผิดชอบด้านข้อมูลประเมินฐานการใช้ ความสอดคล้อง และการแจ้งเจ้าของข้อมูลก่อน", "เปลี่ยนชื่อไฟล์แล้วใช้ได้", "ส่งให้ผู้รับจ้างตัดสินใจ"], a: 1, why: "การใช้ใหม่ต้องประเมินความชอบธรรมและความโปร่งใส ไม่ใช่อาศัยเพียงการครอบครองข้อมูล", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL067", cat: "PRI", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ต้องแชร์รายงานที่มีรายชื่อและผลประเมินกับผู้จัดการเฉพาะกลุ่ม ควรทำอย่างไร", c: ["แชร์ทั้งองค์กร", "ส่งเข้ากลุ่มแชตทั่วไป", "กำหนดสิทธิ์เฉพาะผู้มีหน้าที่และหลีกเลี่ยงลิงก์สาธารณะ", "อัปโหลดบัญชีส่วนตัว"], a: 2, why: "หลัก need-to-know จำกัดผู้เข้าถึงตามหน้าที่", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL068", cat: "PRI", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ส่งไฟล์ข้อมูลส่วนบุคคลผิดผู้รับและเพิ่งทราบทันที ควรทำอย่างไร", c: ["ลบอีเมลจากกล่องส่งแล้วจบ", "รอว่าผู้รับจะเปิดหรือไม่", "ส่งไฟล์เดิมให้คนเพิ่มเพื่อสอบถาม", "แจ้งเหตุผ่านกระบวนการขององค์กร ขอให้ผู้รับลบ และเก็บรายละเอียดเหตุ"], a: 3, why: "การตอบสนองต้องรวดเร็ว จำกัดผลกระทบ และสร้างบันทึกเหตุ", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL069", cat: "PRI", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องแสดงตัวอย่างผลงานนักศึกษาในการอบรมภายนอก ควรทำอย่างไร", c: ["ประเมินสิทธิ์และความจำเป็น ปกปิดข้อมูลระบุตัวตน หรือขออนุญาตตามกระบวนการ", "ใช้ได้ทันทีเพราะเป็นผู้สอน", "ตัดชื่อแต่คงรหัสและภาพใบหน้า", "โพสต์ลิงก์ชั้นเรียน"], a: 0, why: "ควรลดการระบุตัวตนและใช้ตามสิทธิ์/วัตถุประสงค์ที่เหมาะสม", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL070", cat: "PRI", diff: "ยาก", group: "ทุกตำแหน่ง", q: "ระบบใหม่ต้องเก็บข้อมูลจำนวนมากเพื่อ AI วิเคราะห์ในอนาคต แต่ยังไม่มีกรณีใช้งานชัดเจน ควรตัดสินใจอย่างไร", c: ["เก็บทั้งหมดไว้ก่อนเพราะพื้นที่ราคาถูก", "กำหนดวัตถุประสงค์ ประเมินความจำเป็น ความเสี่ยง ระยะเวลาเก็บ และการกำกับก่อนเก็บ", "ให้ AI เลือกข้อมูลเอง", "ขอความยินยอมแบบกว้างที่สุดแล้วจบ"], a: 1, why: "การเก็บแบบเผื่อใช้ขัดกับการจำกัดวัตถุประสงค์และเพิ่มความเสี่ยง", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL071", cat: "PRI", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "ไฟล์หนึ่งมีสิทธิ์เข้าถึงแบบรายบุคคล กลุ่มหน่วยงาน และลิงก์สาธารณะพร้อมกัน ควรตรวจอย่างไร", c: ["ดูเฉพาะรายชื่อบุคคล", "เปลี่ยนสีโฟลเดอร์", "ตรวจสิทธิ์ที่มีผลจริงจากทุกเส้นทางและถอนเส้นทางที่กว้างเกินจำเป็น", "สร้างสำเนาเพิ่ม"], a: 2, why: "สิทธิ์จริงอาจสืบทอดหรือเปิดผ่านลิงก์ จึงต้องตรวจทุกเส้นทาง", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL072", cat: "PRI", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ข้อมูลวิจัยถูกทำให้ไม่แสดงชื่อ แต่ยังมีอายุ ตำแหน่ง และเหตุการณ์เฉพาะที่ชี้ตัวได้ ควรถือว่าอย่างไร", c: ["ไม่ใช่ข้อมูลส่วนบุคคลทันทีที่ลบชื่อ", "เผยแพร่ได้เพราะใช้รหัสแทน", "เพิ่มข้อมูลรายละเอียดเพื่อความโปร่งใส", "ยังมีความเสี่ยงระบุตัวบุคคลได้และต้องประเมินการทำให้ไม่ระบุตัวตนเพิ่ม"], a: 3, why: "การลบตัวระบุโดยตรงอาจยังไม่พอเมื่อข้อมูลประกอบชี้กลับถึงบุคคลได้", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S06", url: "https://ratchakitcha.soc.go.th/documents/17082307.pdf", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL073", cat: "CIT", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Digital Footprint หมายถึงอะไร", c: ["ร่องรอยข้อมูลที่เกิดจากกิจกรรมดิจิทัลของบุคคล", "ขนาดหน้าจอ", "จำนวนแอปในโทรศัพท์", "ความเร็วอินเทอร์เน็ต"], a: 0, why: "กิจกรรมออนไลน์ทิ้งข้อมูลที่อาจคงอยู่และถูกเชื่อมโยงได้", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL074", cat: "CIT", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "เมื่อถูกกลั่นแกล้งทางออนไลน์ สิ่งที่ควรทำคืออะไร", c: ["ตอบโต้ด้วยข้อมูลส่วนตัวของอีกฝ่าย", "เก็บหลักฐาน บล็อกหรือรายงาน และขอความช่วยเหลือจากผู้รับผิดชอบ", "ลบหลักฐานทั้งหมด", "สร้างบัญชีปลอมโจมตีกลับ"], a: 1, why: "การรักษาหลักฐานและใช้ช่องทางช่วยเหลือลดความเสี่ยงและสนับสนุนการจัดการ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL075", cat: "CIT", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ข้อใดช่วยลดอาการล้าจากการใช้หน้าจอ", c: ["เพิ่มความสว่างสูงสุดตลอดเวลา", "นั่งท่าเดิมหลายชั่วโมง", "พักสายตา ปรับท่านั่ง และจัดแสงให้เหมาะสม", "ใช้โทรศัพท์ขณะเดิน"], a: 2, why: "การพักและการยศาสตร์ช่วยลดความล้าทางตาและกล้ามเนื้อ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL076", cat: "CIT", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "ข้อความทางเลือกของรูปภาพ (alt text) มีประโยชน์หลักอย่างไร", c: ["ทำให้ไฟล์เล็กลงเสมอ", "ป้องกันการคัดลอกภาพ", "เพิ่มความเร็วอินเทอร์เน็ต", "ช่วยผู้ใช้โปรแกรมอ่านหน้าจอเข้าใจสาระของภาพ"], a: 3, why: "Alt text ถ่ายทอดความหมายของภาพให้ผู้ที่มองไม่เห็นภาพ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL077", cat: "CIT", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "โพสต์เก่าที่ไม่เหมาะสมถูกค้นพบภายหลัง ข้อใดเป็นบทเรียนสำคัญ", c: ["เนื้อหาออนไลน์อาจถูกบันทึกและมีผลต่อชื่อเสียงแม้ลบต้นฉบับ", "ลบแล้วหายจากทุกที่แน่นอน", "บัญชีส่วนตัวไม่มีผลต่อผู้อื่น", "เปลี่ยนชื่อบัญชีแล้วไม่มีใครเชื่อมโยงได้"], a: 0, why: "รอยเท้าดิจิทัลอาจคงอยู่ผ่านสำเนา ภาพหน้าจอ หรือระบบเก็บถาวร", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL078", cat: "CIT", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "วิดีโออบรมมีเฉพาะเสียงพูด วิธีเพิ่มการเข้าถึงคืออะไร", c: ["เพิ่มเพลงพื้นหลัง", "เพิ่มคำบรรยายที่ถูกต้องและเอกสารประกอบที่เข้าถึงได้", "ลดขนาดตัวอักษร", "ใช้สีแทนคำอธิบายทั้งหมด"], a: 1, why: "คำบรรยายช่วยผู้มีข้อจำกัดการได้ยินและผู้ใช้ในสภาพแวดล้อมต่าง ๆ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL079", cat: "CIT", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ระบบบังคับให้พนักงานใช้สีแดงและเขียวเพื่อแยกสถานะเพียงอย่างเดียว ควรปรับอย่างไร", c: ["เพิ่มความสดของสี", "เปลี่ยนพื้นหลังเป็นภาพ", "เพิ่มข้อความหรือสัญลักษณ์ควบคู่กับสี", "ซ่อนชื่อสถานะ"], a: 2, why: "ไม่ควรใช้สีเป็นสัญญาณเดียวเพราะผู้ใช้บางคนแยกสีไม่ได้", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL080", cat: "CIT", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "กลุ่มแชตงานมีข้อความนอกเวลาจำนวนมาก วิธีใดเหมาะสมที่สุด", c: ["ออกจากกลุ่มถาวร", "ตอบทุกข้อความทันที", "ส่งข้อความซ้ำหลายช่อง", "กำหนดกติกาเวลา ความเร่งด่วน และใช้การตั้งค่าแจ้งเตือนอย่างสมดุล"], a: 3, why: "ขอบเขตการสื่อสารและการแจ้งเตือนช่วยทั้งประสิทธิภาพและสุขภาวะ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL081", cat: "CIT", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "เอกสารประกอบการสอนใช้ภาพข้อความจำนวนมาก ผู้ใช้โปรแกรมอ่านหน้าจอเข้าถึงไม่ได้ ควรทำอย่างไร", c: ["ใช้ข้อความจริง โครงสร้างหัวเรื่อง และ alt text ที่สื่อสารความหมาย", "เพิ่มความละเอียดภาพเท่านั้น", "ใส่ข้อความทั้งหมดในคำอธิบายไฟล์", "เปลี่ยนเป็นภาพสีขาวดำ"], a: 0, why: "ข้อความจริงและโครงสร้างเอกสารเข้าถึงและค้นหาได้ดีกว่าภาพข้อความ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL082", cat: "CIT", diff: "ยาก", group: "ทุกตำแหน่ง", q: "นโยบายสื่อสังคมขององค์กรควรสมดุลเรื่องใด", c: ["จำนวนโพสต์ต่อวันเท่านั้น", "เสรีภาพการสื่อสาร ความลับ ความเป็นส่วนตัว ความถูกต้อง และความรับผิดชอบ", "ความนิยมของแพลตฟอร์มเท่านั้น", "ห้ามบุคลากรใช้สื่อออนไลน์ทุกกรณี"], a: 1, why: "การกำกับที่ดีต้องคุ้มครองหลายคุณค่าพร้อมกันและสัมพันธ์กับความเสี่ยง", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL083", cat: "CIT", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "แบบฟอร์มออนไลน์ผ่านทุกช่อง แต่ใช้งานด้วยคีย์บอร์ดไม่ได้ ควรประเมินอย่างไร", c: ["ถือว่าผ่านเพราะมองเห็นได้", "ให้ผู้ใช้ซื้อเมาส์ใหม่", "ถือเป็นปัญหาการเข้าถึงและทดสอบการนำทาง โฟกัส ป้ายกำกับ และข้อความผิดพลาด", "เพิ่มจำนวนสีในแบบฟอร์ม"], a: 2, why: "การเข้าถึงครอบคลุมการโต้ตอบ ไม่ใช่เพียงการมองเห็น", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL084", cat: "CIT", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "AI สร้างคำบรรยายภาพให้เอกสารการสอนอัตโนมัติ ควรใช้วิธีใด", c: ["ใช้ผล AI ทุกภาพโดยไม่ตรวจ", "ลบคำบรรยายเดิมทั้งหมด", "ใช้คำว่า รูปภาพ กับทุกภาพ", "ให้มนุษย์ตรวจความถูกต้อง ความสำคัญตามบริบท และหลีกเลี่ยงการเปิดเผยข้อมูล"], a: 3, why: "คำบรรยายอัตโนมัติอาจผิดหรือไม่สื่อสารจุดประสงค์ของภาพ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL085", cat: "DTR", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "ก่อนชำระเงินร้านค้าออนไลน์ สิ่งใดควรตรวจ", c: ["ตัวตนผู้ขาย เงื่อนไข ราคา ช่องทางชำระ และความน่าเชื่อถือ", "จำนวนสีในหน้าเว็บ", "เพลงในโฆษณา", "ขนาดโลโก้"], a: 0, why: "การตรวจผู้ขายและเงื่อนไขลดความเสี่ยงจากการหลอกลวงและข้อพิพาท", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL086", cat: "DTR", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "OTP ควรปฏิบัติอย่างไร", c: ["บอกเจ้าหน้าที่ที่โทรมาได้", "ไม่เปิดเผยให้ผู้อื่นและใช้เฉพาะธุรกรรมที่ตนเริ่ม", "ส่งในกลุ่มครอบครัว", "เก็บไว้ในโพสต์สาธารณะ"], a: 1, why: "OTP เป็นปัจจัยยืนยันที่ผู้โจมตีสามารถใช้ยึดธุรกรรมได้", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL087", cat: "DTR", diff: "ง่าย", group: "เจ้าหน้าที่", q: "หลักฐานใดควรเก็บหลังทำธุรกรรมออนไลน์", c: ["เฉพาะภาพสินค้า", "เฉพาะชื่อแอป", "รายละเอียดคำสั่งซื้อ ใบยืนยัน การชำระ และเงื่อนไขที่เกี่ยวข้อง", "ไม่ต้องเก็บเพราะระบบจำให้"], a: 2, why: "หลักฐานช่วยตรวจสอบและแก้ข้อพิพาท", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL088", cat: "DTR", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "การลงชื่อท้ายอีเมลอาจเป็นลายมือชื่ออิเล็กทรอนิกส์ได้หรือไม่", c: ["ไม่ได้ทุกกรณี", "ได้เฉพาะเมื่อพิมพ์ด้วยตัวใหญ่", "ได้เฉพาะอีเมลภายใน", "อาจได้ ขึ้นกับวิธีที่ใช้ระบุตัวบุคคลและแสดงเจตนาในบริบทนั้น"], a: 3, why: "กฎหมายธุรกรรมอิเล็กทรอนิกส์พิจารณาวิธีระบุตัวและการแสดงเจตนา ไม่จำกัดเพียงภาพลายเซ็น", secs: 45, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL089", cat: "DTR", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "ได้รับ QR ชำระเงินในแชตจากผู้ขาย แต่ชื่อผู้รับเงินไม่ตรง ควรทำอย่างไร", c: ["หยุดและยืนยันข้อมูลกับช่องทางทางการก่อนชำระ", "ชำระจำนวนเล็กก่อน", "แก้ชื่อบนภาพ QR", "ส่งต่อให้คนอื่นทดลอง"], a: 0, why: "ชื่อผู้รับไม่ตรงเป็นสัญญาณให้ตรวจสอบก่อนยืนยันธุรกรรม", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL090", cat: "DTR", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "เว็บไซต์ขายของเลียนแบบโดเมนร้านดังและเร่งให้จ่ายทันที ควรประเมินอย่างไร", c: ["เชื่อเพราะมี HTTPS", "ตรวจโดเมน ช่องทางติดต่อ เงื่อนไข และเข้าสู่ร้านจากช่องทางทางการ", "เชื่อเพราะลดราคาสูง", "เชื่อเพราะมีรีวิวในหน้าเดียวกัน"], a: 1, why: "HTTPS ไม่ยืนยันตัวผู้ขาย ต้องตรวจหลายสัญญาณและต้นทาง", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL091", cat: "DTR", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "ต้องจัดซื้อบริการออนไลน์แบบต่ออายุอัตโนมัติ ควรบันทึกข้อมูลใด", c: ["เฉพาะรหัสผ่าน", "เฉพาะโลโก้บริการ", "เจ้าของบัญชี รอบเรียกเก็บ เงื่อนไขยกเลิก งบประมาณ และผู้อนุมัติ", "ไม่ต้องบันทึกเพราะหักอัตโนมัติ"], a: 2, why: "การกำกับวงจรสมาชิกป้องกันค่าใช้จ่ายตกค้างและบัญชีไร้เจ้าของ", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL092", cat: "DTR", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ได้รับเอกสารให้ลงนามอิเล็กทรอนิกส์จากผู้ส่งที่ไม่คุ้นเคย ควรทำอย่างไร", c: ["ลงนามทันทีเพราะระบบมีโลโก้", "ส่งต่อให้ผู้อื่นลงนามแทน", "ดาวน์โหลดโปรแกรมจากลิงก์แนบ", "ยืนยันผู้ส่ง วัตถุประสงค์ เอกสาร และช่องทางลงนามก่อนดำเนินการ"], a: 3, why: "ระบบลงนามอาจถูกใช้ทำฟิชชิง จึงต้องยืนยันธุรกรรมและผู้ส่ง", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL093", cat: "DTR", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องใช้ภาพสัญญาอนุญาต CC BY ในสื่อการสอน ควรทำอย่างไร", c: ["ให้เครดิตผู้สร้าง ระบุแหล่งและสัญญาอนุญาต และบอกเมื่อมีการดัดแปลง", "ลบชื่อผู้สร้าง", "ใช้ได้โดยไม่อ้างอิงเพราะไม่ขาย", "ใส่คำว่า Google Image"], a: 0, why: "CC BY อนุญาตใช้ได้ภายใต้เงื่อนไขการแสดงที่มา", secs: 75, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL094", cat: "DTR", diff: "ยาก", group: "ทุกตำแหน่ง", q: "องค์กรจะรับเอกสารยืนยันผ่านการคลิกปุ่มแทนลายเซ็น วิธีใดทำให้หลักฐานน่าเชื่อถือขึ้น", c: ["ใช้ปุ่มสีแดง", "ยืนยันตัวผู้ใช้ เก็บเวลา เนื้อหาที่ตกลง และบันทึกเหตุการณ์ที่แก้ไขย้อนหลังได้ยาก", "ให้ผู้ใช้คลิกซ้ำสองครั้ง", "เก็บเฉพาะภาพหน้าจอปุ่ม"], a: 1, why: "ความน่าเชื่อถือขึ้นกับการเชื่อมตัวบุคคล เจตนา เนื้อหา และหลักฐานตรวจสอบย้อนหลัง", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL095", cat: "DTR", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "ใบเสนอราคาถูกเปลี่ยนเลขบัญชีระหว่างส่งอีเมล วิธีควบคุมใดเหมาะที่สุด", c: ["เชื่ออีเมลล่าสุดเสมอ", "ให้ผู้ขายส่งไฟล์ไม่มีรหัสผ่าน", "ยืนยันการเปลี่ยนข้อมูลการเงินผ่านช่องทางแยกและใช้กระบวนการอนุมัติหลายฝ่าย", "เปลี่ยนสีเลขบัญชี"], a: 2, why: "การยืนยันนอกช่องทางและแบ่งหน้าที่ลดความเสี่ยง Business Email Compromise", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL096", cat: "DTR", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องเผยแพร่สื่อที่ดัดแปลงจากหลายแหล่งซึ่งใช้สัญญาอนุญาตต่างกัน ควรทำอย่างไร", c: ["ใช้สัญญาอนุญาตที่เปิดที่สุดกับงานทั้งหมด", "ตัดที่มาบางแหล่งออก", "เผยแพร่ก่อนแล้วค่อยขออนุญาต", "ตรวจเงื่อนไขแต่ละสัญญา ความเข้ากันได้ และจัดทำรายการที่มาครบ"], a: 3, why: "งานผสมต้องเคารพเงื่อนไขของทุกองค์ประกอบและความเข้ากันได้ของสัญญา", secs: 105, status: "draft", legal: "ต้องทบทวน", src: "S08", url: "https://www.etda.or.th/th/Useful-Resource/กฎหมาย-HTML/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์/พระราชบัญญัติว่าด้วยธุรกรรมทางอิเล็กทรอนิกส์-พ-ศ-2544.aspx", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL097", cat: "AIL", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Generative AI ทำหน้าที่หลักอย่างไร", c: ["สร้างผลลัพธ์ใหม่จากรูปแบบที่เรียนรู้จากข้อมูล", "รับรองความจริงทุกคำตอบ", "แทนที่ฐานข้อมูลต้นฉบับ", "ตัดสินใจทางกฎหมายได้อัตโนมัติ"], a: 0, why: "Generative AI สร้างข้อความ ภาพ หรือข้อมูลใหม่ แต่ไม่รับประกันความถูกต้อง", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL098", cat: "AIL", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Hallucination ของ AI หมายถึงอะไร", c: ["AI หยุดทำงานเพราะไฟดับ", "ผลลัพธ์ที่ดูน่าเชื่อแต่ไม่ถูกต้องหรือไม่มีหลักฐาน", "หน้าจอกะพริบ", "ผู้ใช้ลืมรหัสผ่าน"], a: 1, why: "โมเดลอาจสร้างข้อมูลผิดที่มีรูปแบบน่าเชื่อถือ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL099", cat: "AIL", diff: "ง่าย", group: "เจ้าหน้าที่", q: "ข้อมูลใดไม่ควรใส่ใน AI สาธารณะโดยไม่มีการอนุมัติ", c: ["ข้อความประชาสัมพันธ์ที่เผยแพร่แล้ว", "คำถามทั่วไปที่ไม่มีข้อมูลภายใน", "ข้อมูลส่วนบุคคลหรือข้อมูลลับขององค์กร", "ตัวอย่างสมมุติที่ไม่ระบุตัวบุคคล"], a: 2, why: "การส่งข้อมูลลับไปบริการภายนอกอาจทำให้สูญเสียการควบคุมข้อมูล", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL100", cat: "AIL", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "ก่อนส่งอีเมลที่ AI ร่างให้ผู้บริหาร ควรทำอะไร", c: ["ส่งทันทีเพราะภาษาเรียบร้อย", "ลบหัวเรื่อง", "ให้ AI เป็นผู้อนุมัติ", "ตรวจข้อเท็จจริง น้ำเสียง ผู้รับ และข้อมูลลับ"], a: 3, why: "มนุษย์ยังต้องรับผิดชอบต่อความถูกต้องและความเหมาะสมของข้อความ", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL101", cat: "AIL", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "AI ให้ตัวเลขพร้อมอ้างงานวิจัยที่ค้นไม่พบ ควรทำอย่างไร", c: ["ถือว่ายังไม่ยืนยันและตรวจจากแหล่งต้นฉบับที่เชื่อถือได้", "ใช้เพราะ AI ระบุชื่อวารสาร", "เปลี่ยนปีให้ดูใหม่", "อ้าง AI แทนแหล่งข้อมูล"], a: 0, why: "การอ้างอิงที่สร้างขึ้นอาจไม่มีจริง ต้องตรวจแหล่งต้นฉบับ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL102", cat: "AIL", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "ต้องการลดความลำเอียงของ AI ในการสรุปใบสมัคร ควรทำอย่างไร", c: ["ให้ AI เลือกผู้สมัครเองทั้งหมด", "กำหนดเกณฑ์งานชัด ปกปิดข้อมูลไม่เกี่ยวข้อง ตรวจผลหลายกลุ่ม และให้มนุษย์ทบทวน", "ใช้ข้อมูลส่วนตัวเพิ่ม", "เลือกโมเดลที่ตอบเร็วที่สุด"], a: 1, why: "การลด bias ต้องจัดการทั้งข้อมูล เกณฑ์ การทดสอบ และการกำกับ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL103", cat: "AIL", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "Prompt ที่ดีสำหรับสรุปรายงานควรมีองค์ประกอบใด", c: ["คำว่า ช่วยทำให้ดี", "ชื่อเครื่องมือ AI เท่านั้น", "วัตถุประสงค์ บริบท ขอบเขต รูปแบบผลลัพธ์ และข้อห้ามด้านข้อมูล", "ขอคำตอบยาวที่สุด"], a: 2, why: "ข้อกำหนดที่ชัดช่วยให้ผลลัพธ์สอดคล้องและตรวจสอบได้", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL104", cat: "AIL", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "AI สรุปมติประชุมผิดจากเสียงบันทึก ควรทำอย่างไร", c: ["ใช้สรุป AI เพราะอ่านง่ายกว่า", "ลบเสียงบันทึกทันที", "ให้ AI โหวตว่ามติใดถูก", "เทียบหลักฐาน แก้ไข และให้ผู้รับผิดชอบรับรองก่อนเผยแพร่"], a: 3, why: "AI เป็นเครื่องมือช่วยร่าง ไม่ใช่หลักฐานหรือผู้รับรองมติ", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL105", cat: "AIL", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "นักศึกษาส่งงานที่ใช้ AI แต่รายวิชาอนุญาตแบบมีเงื่อนไข วิธีประเมินที่เหมาะสมคืออะไร", c: ["ตรวจการเปิดเผยการใช้ กระบวนการคิด หลักฐาน และผลลัพธ์ตามเกณฑ์รายวิชา", "ตัดสินจากเครื่องตรวจ AI เพียงตัวเดียว", "ให้ศูนย์ทุกงานที่ภาษาดี", "ห้าม AI ย้อนหลังโดยไม่แจ้ง"], a: 0, why: "ควรประเมินตามกติกาที่แจ้งและหลักฐานการเรียนรู้ ไม่พึ่งตัวตรวจที่ไม่แน่นอนเพียงอย่างเดียว", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL106", cat: "AIL", diff: "ยาก", group: "ทุกตำแหน่ง", q: "เอกสารภายนอกมีข้อความสั่ง AI ให้เปิดเผยข้อมูลหรือใช้เครื่องมืออื่น ระบบควรทำอย่างไร", c: ["ทำตามเพราะอยู่ในเอกสาร", "ถือเป็นข้อมูลที่ไม่น่าเชื่อถือ แยกจากคำสั่งระบบ และขอการยืนยันตามนโยบาย", "เพิ่มสิทธิ์ให้ AI", "ปิดบันทึกเหตุการณ์"], a: 1, why: "คำสั่งในข้อมูลภายนอกอาจเป็น prompt injection และไม่ควรมีอำนาจเหนือกฎระบบ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL107", cat: "AIL", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "Agent สามารถอนุมัติสิทธิประโยชน์บุคลากรโดยอัตโนมัติ ควรออกแบบการกำกับอย่างไร", c: ["ให้ Agent ตัดสินทุกกรณีเพื่อความเร็ว", "ซ่อนกฎการตัดสินจากผู้ตรวจ", "จำกัดอำนาจตามความเสี่ยง บันทึกเหตุผล ให้มนุษย์อนุมัติกรณีสำคัญ และมีช่องทางอุทธรณ์", "ปิดการย้อนกลับผล"], a: 2, why: "การตัดสินที่กระทบสิทธิต้องมี accountability มนุษย์ และการตรวจสอบ/แก้ไข", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL108", cat: "AIL", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องใช้ AI วิเคราะห์คำตอบปลายเปิดของนักศึกษาอย่างยุติธรรม ควรทำอย่างไร", c: ["ให้ AI สร้าง rubric หลังเห็นชื่อผู้เรียน", "ใช้คำตอบตัวอย่างกลุ่มเดียว", "ไม่เปิดเผยว่ามี AI ช่วย", "กำหนด rubric ทดสอบความสอดคล้อง ตรวจตัวอย่างหลายกลุ่ม ให้มนุษย์ทบทวน และไม่ใช้ผลเดี่ยวตัดสิน"], a: 3, why: "การประเมินต้องทดสอบความเที่ยง ความเป็นธรรม และคงมนุษย์กำกับ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S11", url: "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL109", cat: "PRB", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "เมื่อโปรแกรมทำงานผิดปกติ ขั้นแรกที่เหมาะสมคืออะไร", c: ["บันทึกอาการ ตรวจข้อความผิดพลาด และลองขั้นพื้นฐานที่ปลอดภัย", "ลบข้อมูลทั้งหมด", "ติดตั้งโปรแกรมจากเว็บสุ่ม", "ปิดระบบรักษาความปลอดภัย"], a: 0, why: "ข้อมูลอาการและข้อความผิดพลาดช่วยวินิจฉัยโดยไม่เพิ่มความเสียหาย", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL110", cat: "PRB", diff: "ง่าย", group: "ทุกตำแหน่ง", q: "Automation เหมาะกับงานประเภทใดมากที่สุด", c: ["งานที่ต้องใช้ดุลยพินิจสูงทุกกรณี", "งานซ้ำ มีกฎชัด และข้อมูลนำเข้าเป็นแบบแผน", "งานที่กระบวนการเปลี่ยนทุกวัน", "งานที่ไม่มีเจ้าของ"], a: 1, why: "งานที่เป็นมาตรฐานและซ้ำสามารถทำอัตโนมัติได้เสถียรกว่า", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL111", cat: "PRB", diff: "ง่าย", group: "เจ้าหน้าที่", q: "แหล่งเรียนรู้ใดเหมาะเมื่อฟังก์ชันโปรแกรมเปลี่ยนไป", c: ["โพสต์เก่าที่ไม่ระบุปี", "คำบอกต่อโดยไม่ทดลอง", "คู่มือทางการและแหล่งเรียนรู้ที่ระบุเวอร์ชันล่าสุด", "ไฟล์ที่ไม่ทราบผู้สร้าง"], a: 2, why: "คู่มือทางการและเวอร์ชันช่วยลดการใช้วิธีที่ล้าสมัย", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL112", cat: "PRB", diff: "ง่าย", group: "เลขานุการ/ผู้ประสานงาน", q: "ก่อนเปิดใช้ระบบแจ้งเตือนอัตโนมัติ ควรกำหนดอะไร", c: ["สีข้อความเพียงอย่างเดียว", "จำนวนอีโมจิ", "ให้ระบบส่งทุกเหตุการณ์", "ผู้รับ เหตุการณ์ เนื้อหา เวลา และช่องทางยกเลิกหรือแก้ไข"], a: 3, why: "แจ้งเตือนที่ดีต้องตรงคน ตรงเหตุ และควบคุมได้", secs: 45, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL113", cat: "PRB", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "สูตรเดิมเคยใช้ได้แต่วันนี้ข้อมูลใหม่ทำให้ผิดพลาด ควรตรวจอะไร", c: ["รูปแบบข้อมูล ค่าว่าง ช่วงสูตร และตัวอย่างแถวที่ผิด", "เปลี่ยนแบบอักษร", "สร้างกราฟใหม่", "คัดลอกผลลัพธ์เก่าทับ"], a: 0, why: "ข้อมูลใหม่อาจละเมิดสมมติฐานของสูตร จึงต้องตรวจอินพุตและขอบเขต", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL114", cat: "PRB", diff: "ปานกลาง", group: "ทุกตำแหน่ง", q: "จะเลือกเครื่องมือดิจิทัลใหม่ให้ทีม ควรประเมินอะไร", c: ["ความนิยมเพียงอย่างเดียว", "ความต้องการผู้ใช้ ความปลอดภัย การเชื่อมต่อ ต้นทุน การสนับสนุน และการเลิกใช้", "จำนวนฟีเจอร์มากที่สุด", "หน้าตาสวยที่สุด"], a: 1, why: "การเลือกเครื่องมือต้องพิจารณาวงจรชีวิตและข้อจำกัดองค์กร", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL115", cat: "PRB", diff: "ปานกลาง", group: "เจ้าหน้าที่", q: "งานคัดลอกข้อมูลจากอีเมลลงตารางเกิดผิดบ่อย วิธีปรับปรุงที่เหมาะคืออะไร", c: ["ให้พิมพ์เร็วขึ้น", "เพิ่มคนคัดลอกโดยไม่มีกติกา", "กำหนดแบบฟอร์มข้อมูล ตรวจ validation และทดสอบการเชื่อมอัตโนมัติ", "ลบข้อมูลที่ผิดโดยไม่หาสาเหตุ"], a: 2, why: "การปรับแหล่งข้อมูลและ validation ลดข้อผิดพลาดที่ต้นทาง", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL116", cat: "PRB", diff: "ปานกลาง", group: "เลขานุการ/ผู้ประสานงาน", q: "ระบบส่งเตือนประชุมซ้ำสามครั้งเพราะหลาย workflow ทำงานทับกัน ควรแก้อย่างไร", c: ["ปิดแจ้งเตือนทั้งหมด", "เพิ่ม workflow ที่สี่", "เปลี่ยนข้อความแต่คง trigger เดิม", "ทำแผนผัง trigger เจ้าของ workflow และกติกาป้องกันรายการซ้ำ"], a: 3, why: "ต้องแก้ที่ตรรกะการเริ่มงานและการกำกับ workflow", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL117", cat: "PRB", diff: "ปานกลาง", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องทดลองเครื่องมือใหม่กับชั้นเรียน วิธีใดลดความเสี่ยง", c: ["ทดลองกลุ่มเล็ก กำหนดผลที่วัดได้ มีทางเลือกสำรอง และเก็บข้อเสนอแนะ", "ใช้ทั้งชั้นทันทีโดยไม่มีแผนสำรอง", "บังคับใช้บัญชีส่วนตัว", "วัดผลจากความรู้สึกผู้สอนเท่านั้น"], a: 0, why: "Pilot ที่มีเกณฑ์และ fallback ช่วยเรียนรู้ก่อนขยายผล", secs: 75, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL118", cat: "PRB", diff: "ยาก", group: "ทุกตำแหน่ง", q: "Workflow อัตโนมัติทำงานเร็วแต่เพิ่มข้อมูลผิดจำนวนมาก ควรประเมินอย่างไร", c: ["เพิ่มความเร็วอีก", "หยุดหรือจำกัดผลกระทบ ตรวจต้นเหตุ คุณภาพอินพุต กฎ validation และการย้อนกลับ", "ซ่อนรายการผิด", "ให้ผู้ใช้แก้เองทีละรายโดยไม่แก้ระบบ"], a: 1, why: "ระบบอัตโนมัติขยายทั้งประโยชน์และข้อผิดพลาด จึงต้องมีการควบคุมและ rollback", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL119", cat: "PRB", diff: "ยาก", group: "เจ้าหน้าที่;เลขานุการ/ผู้ประสานงาน", q: "หน่วยงานมี bot หลายตัวแต่ไม่มีใครทราบว่าใครดูแลเมื่อผิดพลาด ควรกำหนดอะไร", c: ["ชื่อ bot ให้จำง่าย", "ภาพประจำตัว bot", "เจ้าของระบบ ขอบเขตอำนาจ ตัวชี้วัด บันทึกเหตุ ช่องทางหยุด และแผนส่งต่อมนุษย์", "ให้ bot แก้ไขกันเอง"], a: 2, why: "Automation ต้องมี ownership การสังเกตการณ์ และกลไกหยุด/ส่งต่อ", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" },
    { id: "DL120", cat: "PRB", diff: "ยาก", group: "อาจารย์/ผู้เชี่ยวชาญ", q: "ต้องพัฒนาทักษะดิจิทัลของบุคลากรจากผลประเมิน ควรออกแบบแผนอย่างไร", c: ["ส่งหลักสูตรเดียวให้ทุกคน", "วัดจากชั่วโมงอบรมเท่านั้น", "ใช้คะแนนความพึงพอใจเป็นผลลัพธ์เดียว", "เชื่อมช่องว่างทักษะกับงานจริง กิจกรรมฝึก หลักฐานการทำได้ และการประเมินซ้ำ"], a: 3, why: "การพัฒนาที่มีผลต้องผูกกับสมรรถนะงานและหลักฐานการเปลี่ยนแปลง", secs: 105, status: "draft", legal: "ไม่ต้อง", src: "S03", url: "https://joint-research-centre.ec.europa.eu/projects-and-activities/education-and-training/digital-transformation-education/digital-competence-framework-digcomp/digcomp-30_en", verified: "2026-08-01", expiry: "2027-07-31", ver: "1.0" }
  ],
  positions: [
    { id: "asst_president", name: "ผู้ช่วยอธิการบดีด้านทรัพยากรมนุษย์", requiredLevel: 5 },
    { id: "office_director", name: "ผู้อำนวยการสำนักงาน", requiredLevel: 4 },
    { id: "asst_director", name: "ผู้ช่วยผู้อำนวยการ", requiredLevel: 4 },
    { id: "faculty_manager", name: "ผู้จัดการคณะ", requiredLevel: 4 },
    { id: "program_head", name: "หัวหน้าสาขาวิชา", requiredLevel: 4 },
    { id: "dept_head", name: "หัวหน้างาน/แผนก", requiredLevel: 3 },
    { id: "lecturer", name: "อาจารย์", requiredLevel: 3 },
    { id: "officer", name: "เจ้าหน้าที่", requiredLevel: 3 }
  ],
  // คลังคำถามวัดทัศนคติ (ปลายเปิด) — ยังไม่เปิดใช้ในการสอบ เก็บฐานข้อมูลไว้ก่อน
  attitudeBank: {
    columns: ["หมวดคำถาม", "คำถาม"],
    rows: []
  },
  codePrefix: "DL69_",
  // ฐานข้อมูลผู้สมัคร (ดึงจาก Supabase · ตาราง applicants) — ชื่อ-สกุลและตำแหน่งที่สมัครมาจากที่นี่
  supabase: { project: "spu-recruit", table: "applicants", synced: "2 ส.ค. 2569 08:40", source: "Google Sheet ทดสอบ HR DL" },
  applicants: [
    { id: "AP-1001", prefix: "ผู้ช่วยศาสตราจารย์ ดอกเตอร์", first: "วิภา", last: "อัครจินดานนท์", name: "วิภา อัครจินดานนท์", pos: "asst_president", round: "รอบ 1/2569" },
    { id: "AP-1002", prefix: "นางสาว", first: "พรพรรณ", last: "เจียมทองอรุณ", name: "พรพรรณ เจียมทองอรุณ", pos: "office_director", round: "รอบ 1/2569" },
    { id: "AP-1003", prefix: "นาย", first: "กิตติพิชญ์", last: "ทวีภัทรพิทักษ์", name: "กิตติพิชญ์ ทวีภัทรพิทักษ์", pos: "asst_director", round: "รอบ 1/2569" },
    { id: "AP-1004", prefix: "นางสาว", first: "ชนม์ขนิษฐ์", last: "วิศิษฎ์สมบัติ", name: "ชนม์ขนิษฐ์ วิศิษฎ์สมบัติ", pos: "dept_head", round: "รอบ 1/2569" },
    { id: "AP-1005", prefix: "นางสาว", first: "กมลภู", last: "สุวรรณศรี", name: "กมลภู สุวรรณศรี", pos: "officer", round: "รอบ 1/2569" },
    { id: "AP-1006", prefix: "นางสาว", first: "ดวงกมล", last: "สมรูป", name: "ดวงกมล สมรูป", pos: "officer", round: "รอบ 1/2569" },
    { id: "AP-1007", prefix: "นางสาว", first: "กุลดา", last: "พรพระสงฆ์", name: "กุลดา พรพระสงฆ์", pos: "officer", round: "รอบ 1/2569" },
    { id: "AP-1008", prefix: "นางสาว", first: "สุปรียา", last: "สังข์ทอง", name: "สุปรียา สังข์ทอง", pos: "dept_head", round: "รอบ 1/2569" },
    { id: "AP-1009", prefix: "นางสาว", first: "วภัทธิรา", last: "กลิ่นหอม", name: "วภัทธิรา กลิ่นหอม", pos: "officer", round: "รอบ 1/2569" }
  ],
  // สเปกไฟล์ Excel สำหรับนำเข้าข้อสอบ — ตรงกับไฟล์ SPU_DL_Question_Bank
  excelImport: {
    sheet: 'แผ่นงานชื่อ "Question Bank" (หรือแผ่นแรก) · แถวที่ 1 = หัวคอลัมน์ ต้องสะกดตรงตามตาราง',
    accept: ".xlsx, .csv",
    columns: [
      { head: "question_id", req: true, note: "รหัสข้อสอบไม่ซ้ำ รูปแบบ DL001", ex: "DL121" },
      { head: "question_type", req: false, note: "ชนิดข้อสอบ — ระบบรับเฉพาะ MCQ", ex: "MCQ" },
      { head: "category_code", req: true, note: "FND, PRD, INF, COM, SEC, PRI, CIT, DTR, AIL, PRB", ex: "SEC" },
      { head: "difficulty", req: true, note: "ง่าย / ปานกลาง / ยาก", ex: "ปานกลาง" },
      { head: "position_group", req: false, note: 'ทุกตำแหน่ง หรือกลุ่มตำแหน่ง คั่นด้วย ; (เว้นว่าง = ทุกตำแหน่ง)', ex: "ทุกตำแหน่ง" },
      { head: "question", req: true, note: "ข้อความโจทย์", ex: "อีเมลแจ้งให้รีเซ็ตรหัสผ่านด่วน ควรทำอย่างไร" },
      { head: "option_a", req: true, note: "ตัวเลือก A", ex: "กดลิงก์ทันที" },
      { head: "option_b", req: true, note: "ตัวเลือก B", ex: "ตรวจผู้ส่งและแจ้งศูนย์ IT" },
      { head: "option_c", req: true, note: "ตัวเลือก C", ex: "ส่งต่อให้เพื่อนร่วมงาน" },
      { head: "option_d", req: true, note: "ตัวเลือก D", ex: "ตอบกลับด้วยรหัสผ่าน" },
      { head: "correct_answer", req: true, note: "A / B / C / D", ex: "B" },
      { head: "rationale", req: true, note: "เหตุผลของเฉลยสำหรับผู้ตรวจข้อสอบ", ex: "ต้องยืนยันผู้ส่งก่อนเสมอ" },
      { head: "estimated_seconds", req: false, note: "เวลาที่คาดว่าจะใช้ตอบ (ตัวเลข)", ex: "75" },
      { head: "review_status", req: false, note: "รอตรวจทาน / อนุมัติแล้ว / ระงับใช้ (เว้นว่าง = รอตรวจทาน)", ex: "รอตรวจทาน" },
      { head: "legal_review", req: false, note: "ต้อง / ไม่ต้อง — หมวดกฎหมาย PDPA ธุรกรรม ต้องผ่านผู้เชี่ยวชาญก่อนอนุมัติ", ex: "ไม่ต้อง" },
      { head: "source_id", req: false, note: "รหัสแหล่งอ้างอิง เช่น S04", ex: "S04" },
      { head: "source_url", req: false, note: "URL แหล่งอ้างอิง", ex: "https://www.cisa.gov/..." },
      { head: "expiry_date", req: false, note: "วันหมดอายุเนื้อหา YYYY-MM-DD", ex: "2027-07-31" }
    ]
  },
  part2: {
    // อ้างอิงข้อสอบ SPU_DL_Practical_Word_Excel_40pts_20min.docx และ AI Grader Prompt v1
    duration: 20, maxScore: 40, wordMax: 15, excelMax: 25,
    examVersion: "DL_PART2_V1", rubricVersion: "DL_PART2_RUBRIC_V1", promptVersion: "DL_AI_GRADER_V1",
    notice: [
      "เวลาทำข้อสอบรวม 20 นาที ผู้เข้าสอบบริหารเวลา Word และ Excel ได้เอง",
      "คะแนนเต็มส่วนที่ 2 = 40 คะแนน (Word 15 คะแนน / Excel 25 คะแนน)",
      "ห้ามใช้ AI หรือให้บุคคลอื่นช่วยทำข้อสอบ",
      "ส่งไฟล์ผ่านระบบเท่านั้น ครบ 2 ไฟล์ ชื่อไฟล์ต้องผูกกับรหัสผู้เข้าสอบ"
    ],
    word: {
      title: "งานที่ 1 — Microsoft Word (15 คะแนน)",
      scenario: "จัดทำเอกสารแจ้งประชุมสำหรับใช้ภายในมหาวิทยาลัยจากข้อมูลที่กำหนด โดยเอกสารต้องพร้อมนำไปใช้งานจริง",
      data: [
        { k: "ชื่อการประชุม", v: "การประชุมเตรียมความพร้อมโครงการพัฒนาบุคลากร ประจำปีการศึกษา 2569" },
        { k: "วันที่", v: "วันพุธที่ 16 กันยายน 2569" },
        { k: "เวลา", v: "13.30–15.00 น." },
        { k: "สถานที่", v: "ห้องประชุม 1 อาคาร 1" },
        { k: "ผู้เข้าร่วม", v: "หัวหน้าหน่วยงาน เจ้าหน้าที่ผู้รับผิดชอบ และคณะทำงาน" },
        { k: "ผู้ประสานงาน", v: "สำนักงานบุคคล โทร. 1234" }
      ],
      agenda: [
        "สรุปจำนวนผู้เข้าร่วมโครงการ",
        "ตรวจสอบงบประมาณ",
        "แบ่งหน้าที่ผู้รับผิดชอบ",
        "กำหนดวันดำเนินกิจกรรม"
      ],
      rules: [
        "ใช้ TH Sarabun New ขนาด 16 pt สำหรับเนื้อหาทั้งหมด",
        "ใช้ชื่อการประชุมตามที่กำหนด ขนาด 18 pt ตัวหนา และจัดกึ่งกลาง",
        "จัดวาระการประชุมเป็น Numbering อัตโนมัติ",
        "ทำตัวหนาเฉพาะข้อมูล วันที่ เวลา และสถานที่",
        "เอกสารต้องไม่เกิน 1 หน้า และต้องคงข้อมูลสำคัญครบถ้วน",
        "บันทึกไฟล์ตามรหัสผู้เข้าสอบ เช่น เชิญประชุม_DL69_0004.docx"
      ],
      filePrefix: "เชิญประชุม"
    },
    excel: {
      title: "งานที่ 2 — Microsoft Excel (25 คะแนน)",
      scenario: "ตรวจสอบยอดขอเบิกของกิจกรรมก่อนเสนอหัวหน้างาน และจัดทำตารางให้พร้อมใช้งาน",
      columns: ["ลำดับ", "รายการ", "หมวด", "จำนวน", "ราคาต่อหน่วย", "ยอดขอเบิก"],
      rows: [
        ["1", "ค่าอาหารกลางวัน", "อาหาร", "35", "120", "4,200"],
        ["2", "เอกสารประกอบ", "เอกสาร", "35", "45", "1,575"],
        ["3", "ค่าตอบแทนวิทยากร", "วิทยากร", "1", "8,000", "8,000"],
        ["4", "ค่าเช่าห้อง", "สถานที่", "1", "6,000", "6,500"],
        ["5", "อาหารว่าง", "อาหาร", "70", "45", "3,000"],
        ["6", "ค่าบริการระบบออนไลน์", "เทคโนโลยี", "1", "5,500", "5,500"]
      ],
      rules: [
        "ห้ามแก้ไข ลบ หรือสลับลำดับข้อมูลต้นฉบับในคอลัมน์ A–F",
        "เพิ่มคอลัมน์ “ยอดคำนวณ” และใช้ Formula คำนวณจาก จำนวน × ราคาต่อหน่วย สำหรับทุกรายการ",
        "เพิ่มคอลัมน์ “สถานะตรวจสอบ” และใช้ Formula ให้แสดง “ถูกต้อง” เมื่อยอดขอเบิกตรงกับยอดคำนวณ และ “ตรวจสอบ” เมื่อไม่ตรงกัน",
        "ใต้รายการสุดท้าย ให้คำนวณยอดรวมของคอลัมน์ “ยอดคำนวณ” ด้วย SUM",
        "ใช้ Conditional Formatting ที่คอลัมน์ “ยอดคำนวณ” สำหรับค่ามากกว่า 5,000 บาท",
        "ตรวจสอบก่อนส่งว่าไม่มี Formula Error เช่น #VALUE!, #REF!, #DIV/0!",
        "บันทึกไฟล์ตามรหัสผู้เข้าสอบ เช่น ค่าใช้จ่าย_DL69_0004.xlsx"
      ],
      filePrefix: "ค่าใช้จ่าย",
      expected: {
        qty: [35, 35, 1, 1, 70, 1],
        price: [120, 45, 8000, 6000, 45, 5500],
        claim: [4200, 1575, 8000, 6500, 3000, 5500],
        calc: [4200, 1575, 8000, 6000, 3150, 5500],
        status: ["ถูกต้อง", "ถูกต้อง", "ถูกต้อง", "ตรวจสอบ", "ตรวจสอบ", "ถูกต้อง"],
        total: 28425,
        cfThreshold: 5000,
        cfHighlight: [8000, 6000, 5500],
        strictSum: true
      }
    },
    // ข้อมูลที่ใช้ตรวจความครบถ้วน (W1) ฝั่ง Apps Script
    keyFacts: {
      meeting: "การประชุมเตรียมความพร้อมโครงการพัฒนาบุคลากร ประจำปีการศึกษา 2569",
      date: "16 กันยายน 2569",
      time: "13.30",
      place: "ห้องประชุม 1 อาคาร 1",
      attendees: "หัวหน้าหน่วยงาน",
      contact: "1234",
      agenda: [
        "สรุปจำนวนผู้เข้าร่วมโครงการ",
        "ตรวจสอบงบประมาณ",
        "แบ่งหน้าที่ผู้รับผิดชอบ",
        "กำหนดวันดำเนินกิจกรรม"
      ]
    },
    // Rubric ตาม AI Grader Prompt v1 — Word 15 (W1-W6) · Excel 25 (E1-E7)
    rubric: [
      { id: "W1", section: "word", desc: "ความครบถ้วนและความถูกต้องของข้อมูล 10 รายการ", pts: 4 },
      { id: "W2", section: "word", desc: "รูปแบบชื่อการประชุม (18 pt · ตัวหนา · จัดกึ่งกลาง)", pts: 3 },
      { id: "W3", section: "word", desc: "รูปแบบเนื้อหา TH Sarabun New 16 pt", pts: 2 },
      { id: "W4", section: "word", desc: "วาระการประชุมใช้ Numbering อัตโนมัติ", pts: 2 },
      { id: "W5", section: "word", desc: "เน้นตัวหนาที่วันที่ · เวลา · สถานที่", pts: 2 },
      { id: "W6", section: "word", desc: "ไม่เกิน 1 หน้า และชื่อไฟล์ผูกกับรหัสผู้เข้าสอบ", pts: 2 },
      { id: "E1", section: "excel", desc: "รักษาข้อมูลต้นฉบับคอลัมน์ A–F", pts: 2 },
      { id: "E2", section: "excel", desc: "คอลัมน์ยอดคำนวณใช้ Formula จำนวน × ราคาต่อหน่วย (6 รายการ)", pts: 6 },
      { id: "E3", section: "excel", desc: "คอลัมน์สถานะตรวจสอบใช้ Formula เทียบยอด (6 รายการ)", pts: 6 },
      { id: "E4", section: "excel", desc: "รวมยอดคำนวณด้วย SUM ได้ 28,425", pts: 3 },
      { id: "E5", section: "excel", desc: "Conditional Formatting มากกว่า 5,000 บนคอลัมน์ยอดคำนวณ", pts: 4 },
      { id: "E6", section: "excel", desc: "ไม่มี Formula Error ในไฟล์", pts: 2 },
      { id: "E7", section: "excel", desc: "ชื่อไฟล์ถูกต้อง เปิดไฟล์ได้ และโครงสร้างไม่เสีย", pts: 2 }
    ]
  },
  part3: {
    maxScore: 30,
    draftTitle: "ร่างประกาศ (เขียนโดย AI — มีข้อผิดพลาดฝังไว้ 3 จุด)",
    draft: [
      "ประกาศมหาวิทยาลัยศรีปทุม",
      "เรื่อง แนวปฏิบัติการใช้งานระบบสารสนเทศของบุคลากร พ.ศ. 2569",
      "",
      "เพื่อให้การใช้งานระบบสารสนเทศของมหาวิทยาลัยเป็นไปด้วยความเรียบร้อยและปลอดภัย จึงกำหนดแนวปฏิบัติ 5 ข้อ ดังนี้",
      "1. บุคลากรต้องตั้งรหัสผ่านที่คาดเดายาก และเปลี่ยนทุก 90 วัน",
      "2. ห้ามเปิดเผยข้อมูลส่วนบุคคลของนักศึกษาแก่บุคคลภายนอกโดยไม่ได้รับความยินยอม",
      "3. การใช้เครื่องมือ AI ในงานเอกสาร ต้องตรวจทานความถูกต้องก่อนเผยแพร่ทุกครั้ง",
      "4. พบเหตุผิดปกติด้านความปลอดภัย ให้แจ้งศูนย์ ICT ทางอีเมล ict@spu.co.th ภายใน 24 ชั่วโมง",
      "",
      "ทั้งนี้ ตั้งแต่วันที่ 30 กุมภาพันธ์ 2569 เป็นต้นไป",
      "",
      "ประกาศ ณ วันที่ 1 กุมภาพันธ์ 2569"
    ],
    answerKey: [
      { spot: "จำนวนข้อไม่สอดคล้อง", detail: "ระบุว่ามีแนวปฏิบัติ 5 ข้อ แต่ในประกาศมีเพียง 4 ข้อ", fix: "แก้เป็น \u201c4 ข้อ\u201d หรือเพิ่มข้อที่ 5 ให้ครบ" },
      { spot: "อีเมลผิดโดเมน", detail: "ict@spu.co.th ใช้โดเมนเชิงพาณิชย์ .co.th ซึ่งไม่ใช่โดเมนมหาวิทยาลัย", fix: "แก้เป็น ict@spu.ac.th" },
      { spot: "วันที่ไม่มีอยู่จริง", detail: "วันที่ 30 กุมภาพันธ์ 2569 ไม่มีอยู่ในปฏิทิน", fix: "แก้เป็นวันที่ที่มีอยู่จริง เช่น 28 กุมภาพันธ์ 2569 หรือ 1 มีนาคม 2569" }
    ]
  },
  levels: [
    {
      lv: 5, min: 85, name: "Digital Leader", desc: "ใช้ดิจิทัลนำการเปลี่ยนแปลง สอนผู้อื่นได้",
      band: "85 – 100 คะแนน",
      typical: "ปรนัย ≥ 26/30 · ปฏิบัติ ≥ 34/40 · ตรวจงาน AI ≥ 25/30",
      meaning: "ทำครบทุกส่วนแทบไม่มีข้อผิดพลาด จัดรูปแบบเอกสาร ใช้สูตรและตั้งสิทธิ์ Drive ได้ถูกต้องเองทั้งหมด และจับข้อผิดพลาดที่ AI เขียนได้ครบพร้อมอธิบายวิธีแก้",
      action: "มอบงานออกแบบมาตรฐาน/สอนทีมได้ทันที",
      interview: "คำถามระดับออกแบบกระบวนการและวางนโยบาย — ให้เล่าวิธีวางมาตรฐานให้ทีมทั้งหน่วยงาน"
    },
    {
      lv: 4, min: 70, name: "Advanced", desc: "ประยุกต์เครื่องมือดิจิทัลกับงานซับซ้อนได้ดี",
      band: "70 – 84 คะแนน",
      typical: "ปรนัย 21–25/30 · ปฏิบัติ 28–33/40 · ตรวจงาน AI 18–24/30",
      meaning: "ทำงานเอกสารและตารางคำนวณระดับซับซ้อนได้ด้วยตนเอง พลาดรายละเอียดปลีกย่อย 1–2 จุด และตรวจพบข้อผิดพลาดที่ AI เขียนได้เกือบครบ",
      action: "รับงานที่ต้องตัดสินใจเองได้ ต้องการเพียงการทบทวนก่อนเผยแพร่",
      interview: "คำถามระดับประยุกต์และแก้ปัญหาเฉพาะหน้า — เจาะจุดที่พลาดในส่วนปฏิบัติ"
    },
    {
      lv: 3, min: 55, name: "Proficient", desc: "ทำงานประจำด้วยเครื่องมือดิจิทัลได้คล่อง",
      band: "55 – 69 คะแนน",
      typical: "ปรนัย 17–20/30 · ปฏิบัติ 22–27/40 · ตรวจงาน AI 12–17/30",
      meaning: "ทำงานประจำได้ครบถ้วน แต่ยังไม่ครบเกณฑ์ขั้นสูง เช่น ตั้ง Conditional Formatting หรือสิทธิ์แชร์ Drive ไม่ถูก และตรวจพบข้อผิดพลาดของ AI ได้ประมาณครึ่งหนึ่ง",
      action: "ปฏิบัติงานประจำได้ ควรอบรมเสริมเฉพาะทักษะที่ตก",
      interview: "คำถามระดับปฏิบัติงานจริง — ให้อธิบายขั้นตอนที่ทำในไฟล์และวิธีตรวจทานงาน"
    },
    {
      lv: 2, min: 40, name: "Basic", desc: "ใช้งานพื้นฐานได้ ต้องพัฒนาเพิ่ม",
      band: "40 – 54 คะแนน",
      typical: "ปรนัย 12–16/30 · ปฏิบัติ 16–21/40 · ตรวจงาน AI 6–11/30",
      meaning: "เปิด-แก้-บันทึกไฟล์และพิมพ์งานพื้นฐานได้ แต่ทำโจทย์ขั้นสูงไม่ครบ (สูตร SUM / กฎเงื่อนไข / สิทธิ์ Drive) และมักตรวจไม่พบข้อผิดพลาดที่ AI สร้าง เช่น อีเมลผิดโดเมนหรือวันที่ไม่มีจริง",
      action: "รับได้เฉพาะงานที่มีพี่เลี้ยง ต้องเข้าอบรมก่อนรับงานเอกสารทางการ",
      interview: "คำถามระดับพื้นฐาน — ตรวจว่ารู้จักเครื่องมือจริงหรือไม่ และเปิดใจเรียนรู้เพียงใด"
    },
    {
      lv: 1, min: 0, name: "Beginner", desc: "ต้องได้รับการพัฒนาอย่างเป็นระบบ",
      band: "0 – 39 คะแนน",
      typical: "ปรนัย ≤ 11/30 · ปฏิบัติ ≤ 15/40 · ตรวจงาน AI ≤ 5/30",
      meaning: "ยังทำโจทย์ปฏิบัติไม่ผ่านเกณฑ์ส่วนใหญ่ และไม่สามารถระบุข้อผิดพลาดในงานที่ AI เขียนได้",
      action: "ยังไม่พร้อมกับงานที่ต้องใช้ดิจิทัลเป็นหลัก ต้องพัฒนาแบบมีหลักสูตร",
      interview: "คำถามระดับคัดกรอง — ประเมินความคุ้นเคยกับคอมพิวเตอร์และความตั้งใจพัฒนา"
    }
  ],
  timers: { part1: 20 * 60, part2: 20 * 60, part3: 10 * 60 },
  weights: { part1: 30, part2: 40, part3: 30 },
  // ไฟล์จำลองสำหรับการอัปโหลดส่วนที่ 2 (เดโมการ validate)
  mockFiles: [
    { name: "เชิญประชุม_{ชื่อ}.docx", kind: "docx", valid: true },
    { name: "ค่าใช้จ่าย_{ชื่อ}.xlsx", kind: "xlsx", valid: true },
    { name: "เชิญประชุม_{ชื่อ}.pdf", kind: "pdf", valid: false, why: "นามสกุลไฟล์ไม่ตรง (ต้องเป็น .docx)" },
    { name: "งานของฉัน.xlsx", kind: "xlsx", valid: false, why: "ชื่อไฟล์ไม่ตรงรูปแบบ ค่าใช้จ่าย_ชื่อ-สกุล" },
    { name: "ค่าใช้จ่าย_{ชื่อ}_เสีย.xlsx", kind: "xlsx", valid: false, why: "ไฟล์เสียหาย เปิดอ่านไม่ได้" }
  ]
};
